- build.gradle
- src/test/java/uk/gov/register/presentation/functional/FunctionalTestBase.java
- src/test/java/uk/gov/register/presentation/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/presentation/functional/RepresentationsTest.java
- src/test/java/uk/gov/register/presentation/functional/testSupport/TestCurrentKeyDAO.java
Trello: https://trello.com/c/KEPR1o2b
changes:
- make `@Ignore` tests run again
- fix the register name configuration inconsistency
- eg. `VerifiableLogFunctionalTest` change into a unit test on `VerifiableLogResource` using a mocked `EntryQueryDAO`
> Post merge apps fixes

- build.gradle
- src/main/java/uk/gov/register/presentation/resource/RequestContext.java
This supersedes openregister/presentation#255 by doing the Right Thing instead.
(warning: "scheme" and "protocol" are used interchangably here).
Currently, the app uses the scheme in the http request to the app server
to determine what scheme to use in URLs rendered as links (in html and
ttl formats, among others).
This is problematic because the scheme used to access an individual app
server might differ from the scheme used by a user to access the edge
server.
This can be resolved by use of the X-Forwarded-Proto header, which is
set by (among other things) Amazon Elastic Load Balancers (ELBs).  This
header is used to report what the edge request protocol was, rather than
using the individual app server protocol.
> X forwarded proto

- build.gradle
- create_schema.sh
- src/main/java/uk/gov/register/presentation/representations/RepresentationWriter.java
- src/main/java/uk/gov/register/presentation/representations/YamlWriter.java
- src/test/resources/conformance-app-config.yaml
This commit re-enables the conformance tests that were removed during
the early stages of merging the apps.  In doing this, I've copied over
the previous strategy of starting up an app in the gradle file and
cloning/running the conformance tests.  However I've done some changes:
1) where possible, I define tasks and dependencies between tasks, rather
than as doFirst() or doLast() blocks.  In particular, the conformance
tests are run as part of the build by making the `check` task depend on
the conformance task. [1]
This has the advantage, among other things, that you are able to run the
conformance tests separately by running `./gradlew runConformanceTests`
now.
2) I have created a separate config file for running the app in
conformance test mode -- `conformance-app-config.yaml`.  This …
> reinstate conformance tests

- build.gradle
- external-dependencies.gradle
- src/main/java/uk/gov/mint/auth/MintAuthenticator.java
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/presentation/dao/EntryQueryDAO.java
- src/test/java/uk/gov/register/presentation/functional/ApplicationTest.java
- src/test/java/uk/gov/register/presentation/functional/testSupport/TestDAO.java
Relatively painless upgrade.  Release notes:
http://www.dropwizard.io/1.0.0/docs/about/release-notes.html#v1-0-0-jul-26-2016
The main difference that affected us is that the dropwizard-java8 stuff
has been merged into the main dropwizard code, so some packages were
renamed and some stuff went away (such as the Java8Bundle, which is
included by default).
> bump to dropwizard 1.0.0

- deploy/scripts/start-service.sh
I noticed a comment in our terraform code:
https://github.com/openregister/deployment/blob/89c812d0660e01065d25327dd764360db139b57f/aws/modules/instance/main.tf#L15-L16
```
// should be this once we've fixed the app startup script to use the Register tag:
// Name = "${var.vpc_name}-${var.id}-${count.index +1}"
Name = "${var.id}"
```
The comment is saying that the Name tag is set to the name of the
register, but it should instead be set to a meaningful name for the app
server.  Since there can be more than one app server per register, we
have lots of duplicate Names for our app servers.
The Register tag is available if you want to know what the register is.
The start-service.sh script needs to know the register name in order to
fetch the app configuration from S3.  Before this commit, it …
> use the Register tag, not the Name tag, for config

- Procfile
- build.gradle
- heroku.yaml
I got this deployed to heroku. This was a wonderful yak shave:
- heroku is based on logging to console rather than to file
- trying to enable a logger by configuring it with `type: console` resulted in weird errors
- these errors were caused by our fat jar not concatenating metadata properly
- rather than fixing our home-grown fat jar code, I replaced it with the shadowJar plugin.
After this PR, there is a thin jar at `build/libs/openregister-java.jar` and a far jar at `build/libs/openregister-java-all.jar`.  The fat jar is used for everything -- in particular, starting the app for conformance test, and for copying into the .zip file which is uploaded to S3 for CodeDeploy.
> Allow openregister-java to be deployed to heroku

- src/main/java/uk/gov/register/RegisterApplication.java
- src/test/java/uk/gov/organisation/client/TestJerseyClientBuilder.java
Since we moved to Dropwizard 1.0, Java 8 is supported by default.  This
means that the Jdk8Module and the JavaTimeModule are automatically
supported by Jackson.newObjectMapper(), and we don't need to add them
separately.
> Remove dead code

- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/home.html
- src/test/java/uk/gov/register/resources/HomePageResourceTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
For large registers, each time we redeploy we'll trash the in-memory
cache of merkle tree nodes.  If we have the root hash on the homepage,
then each time we redeploy, we won't be able to render the homepage
until the in-memory cache has been rebuilt.
Reverting back to the static mockup for the time being.
> remove dynamic register proof from home page

- build.gradle
When a test fails, it's hard to see which one failed because it's lost
in the noise of all the PASSED tests in the output.
We originally added this output to give us confidence that the tests
were actually being run.  I don't think we need that any more.
> don't show PASSED tests in build output

- src/main/java/uk/gov/register/AssetsBundleCustomErrorHandler.java
- src/main/java/uk/gov/register/util/RegisterNameExtractor.java
- src/test/java/uk/gov/register/functional/AssetsBundleCustomErrorHandlerTest.java
Any 404 within the AssetsBundle path (eg /assets/not-found ) will
currently break.  This is because the `renderedCopyrightText` variable
is not set, causing the template engine to break.
Also, the error handler was the last place still getting the register
name from the Host header rather than from the register configuration.
I took the opportunity to replace that.
> fix AssetsBundle 404s, remove RegisterNameExtractor

- external-dependencies.gradle
- src/main/java/uk/gov/register/RegisterApplication.java
This means that the MemoizationStore doesn't get too large.
This was part of a commit to the Presentation repo which didn't get merged into the openregister-java repo https://github.com/openregister/presentation/commit/0dfd3c3d0c7505269d9c2656ebf6ad94b499eef5.
> Use InMemoryPowOfTwoNoLeaves to memoize merkle tree hashes

- src/main/java/uk/gov/register/RegisterApplication.java
EntryQueryDAO is now created as requred by EntryLog, and so isn't needed
to be available for injection here.
> remove unused entryQueryDAO

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/core/EntryLog.java
- src/main/java/uk/gov/register/core/ItemStore.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/Register.java
- src/main/java/uk/gov/register/db/EntryQueryDAO.java
- src/main/java/uk/gov/register/db/RecordIndex.java
- src/main/java/uk/gov/register/exceptions/NoSuchItemException.java
- src/main/java/uk/gov/register/resources/DataUpload.java
- src/main/java/uk/gov/register/service/RegisterService.java
- src/main/java/uk/gov/register/store/BackingStoreDriver.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriver.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriverNonTransactional.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriverTransactional.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresDriverTransactionalFunctionalTest.java
- src/test/java/uk/gov/register/store/postgres/PostgresDriverNonTransactionalTest.java
- src/test/java/uk/gov/register/store/postgres/PostgresDriverTestBase.java
- src/test/java/uk/gov/register/store/postgres/PostgresDriverTransactionalTest.java
I have not added any new functionality, only refactored what already exists. 
I've separated database transactions and batching from atomic operations on a register, but created a mapping between the two (in `RegisterService`). 
The `PostgresDriverTransactional` manages a list of staged items, entries and current keys. These are batched up and inserted into the database at certain points. This is managed using a read/write barrier. Whenever there is a read across the whole register, the staged data is written to the database.
I have also changed the Register interface to only implement append-entry and put-item write operations. This will help make sure that all loading code will use the same operations on the Register object instead of duplicating code.
> Separate database transactions from register

- doc/arch/adr-005-tsv-does-not-support-escaping.md
This documents a decision we made a long time ago but hadn't written
down.
> Architecture decision record: TSV doesn't allow escaping

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/configuration/RegisterFieldsConfiguration.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/resources/SearchResource.java
- src/main/java/uk/gov/register/service/RegisterService.java
- src/test/java/uk/gov/register/core/PostgresRegisterTest.java
- src/test/java/uk/gov/register/resources/SearchResourceTest.java
SearchResource shouldn't redirect to /records if the given field name doesn't exist in the current register, but should instead return a 404.
Refactored the checking of an existence of a field in a register into RegisterFieldsConfiguration, which is used in both SearchResource and PostgresRegister (although the latter may not technically need to be checking  this any longer if all requests first go through SearchResource).
> Checking field exists in SearchResource

- src/main/java/uk/gov/register/filters/ContentSecurityPolicyFilter.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/main/java/uk/gov/register/views/representations/ExtraMediaType.java
- src/main/resources/templates/main.html
- src/test/java/uk/gov/register/functional/AnalyticsFunctionalTest.java
- src/test/java/uk/gov/register/functional/ApplicationTest.java
- src/test/java/uk/gov/register/resources/HomePageResourceTest.java
This extracts the inline GA tracking id code into a new dynamic endpoint
so that we don't need to use a nonce or hash in the CSP.
The nonce was a problem because we hardcoded a single value that was
reused, which means that an XSS attacker could also reuse that nonce,
removing the security property of the CSP.
Tested locally using a throwaway GA tracking code.
> Fix Content-Security-Policy

- src/main/java/uk/gov/register/serialization/AddItemCommand.java
- src/main/java/uk/gov/register/serialization/AppendEntryCommand.java
- src/main/java/uk/gov/register/serialization/AssertRootHashCommand.java
- src/main/java/uk/gov/register/serialization/RegisterCommand.java
- src/main/java/uk/gov/register/service/RegisterSerialisationFormatService.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriverTransactional.java
- src/test/java/uk/gov/register/service/RegisterSerialisationFormatServiceTest.java
- src/test/java/uk/gov/register/store/postgres/PostgresDriverTransactionalTest.java
This removes entry-number from the `RegisterCommand.execute` interface as it is not required by all commands. Instead the next entry number is obtained from the `register` object.
To make sure this does not go the database for all commands actions, `PostgresDriverTransactional.getEntries()` has been changed to read the max entry number from the staged entries if there are any present. Otherwise, it goes to the database.
> Remove entry number from register command

- src/main/java/uk/gov/register/resources/EntryResource.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
Previously we would return 500 if the query string contained values that could not be parsed into an Integer; this is not correct as the error lies with the client and should be in the 4xx range. Example: 
```
$ curl -I  "https://country.register.gov.uk/records?page-size=not-a-number"
HTTP/1.1 500 Internal Server Error
...
```
[`IntParam`](http://www.dropwizard.io/0.7.0/dropwizard-jersey/apidocs/io/dropwizard/jersey/params/IntParam.html) is the magic that makes this easy and we should probably use it for `PathParam`s that take integers too.
> Return Bad Request when a user sends a non-integer value

- src/main/resources/templates/400.html
- src/main/resources/templates/404.html
- src/main/resources/templates/500.html
- src/main/resources/templates/download.html
- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/home.html
- src/main/resources/templates/item.html
- src/main/resources/templates/main.html
- src/main/resources/templates/not-implemented.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
https://trello.com/c/sUnoWz2L/490-bug-empty-h1-on-every-page
When only `header` was used both TAGs header were pulled on the page regardless of their fragment names, hence the second one page-header was rendered empty where it should not
This also adds a mapper to catch our not implemented/unsupported operation exception and renders dedicated page for it.
> Fix useless header tag + unimplemented exception

- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/AnalyticsFunctionalTest.java
- src/test/java/uk/gov/register/functional/ApplicationTest.java
- src/test/java/uk/gov/register/functional/AssetsBundleCustomErrorHandlerTest.java
- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
- src/test/java/uk/gov/register/functional/DataDownloadResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/EntriesResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/FindEntityTest.java
- src/test/java/uk/gov/register/functional/FunctionalTestBase.java
- src/test/java/uk/gov/register/functional/HomePageFunctionalTest.java
- src/test/java/uk/gov/register/functional/ItemResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordListResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RepresentationsFunctionalTest.java
- src/test/java/uk/gov/register/functional/VerifiableLogResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
- src/test/resources/test-app-config.yaml
This introduces a RegisterRule abstraction and removes the old FunctionalTestBase.  This results in cleaner, easier to understand tests which are written at the right level of abstraction.
See individual commits for details.
The implementation of RegisterRule is a little messy 🙈 but it's for the greater good! :rage1:
> Introduce register rule

- deploy/scripts/start-service.sh
If the container dies then we can have the Docker service automatically restart the container. We should see less downtime when apps die in environments where there is little or no redundancy.
> Restart Docker app containers that haven't explicitly been stopped

- deploy/scripts/start-service.sh
This should mean that even though our apps might exhaust the available heap they won't also kill the container they run in. You will get a `java.lang.OutOfMemoryError` exception rather than the JVM dying completely.
This is only really sensible to do given we only run one app container on a given instance; if we start running multiple app containers on the same instance we will probably need to look at using cgroups to limit memory and adjusting the heap size from `/sys/fs/cgroup/memory/memory.limit_in_bytes`.
> Choose a JVM max heap size derived from the host's total RAM

- src/main/resources/assets/js/analytics-download-type.js
- src/main/resources/assets/js/analytics-external-links.js
- src/main/resources/assets/js/analytics.js
when navigating to external links or downloading the data on all browsers
The problem was that firefox was redirecting before the ga event was sent. The solution is to cancel browser default action, send GA event and then continue (with timeout on GA event). Google analytics: 
https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#knowing_when_the_hit_has_been_sent
https://trello.com/c/8jMQNDqA/488-bug-google-analytics-events-for-download-page-aren-t-tracked-in-firefox-exception-handling
> Enhance all the things - make sure that GA events are fired 

- src/main/resources/assets/js/analytics.js
Just a cleanup of GA code, variable used as a flag in GA timeout and callback can be (and should be) local.
> Make sure variables (callbackExecuted flag) used in analytics.js codes are not global

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/filters/CorsBundle.java
The code to set up the CrossOriginFilter is pretty generic, in that it
could easily be applied to other projects without modification.  We
can extract this into a Bundle and try to keep the RegisterApplication
smaller.
I hardcoded the specific CORS configuration values for the moment.  If
we ever do extract CorsBundle into a library, we can turn it into a
ConfiguredBundle at that point.
> extract CorsBundle

- src/main/resources/templates/record.html
This should only display in on record pages for the register register.
There are plans to build some kind of RegisterResolver to resolve register URLs
but that will be part of a later pull request.
> Add `View this register` link for record pages in the register register

- build.gradle
- deploy/scripts/start-service.sh
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
This changes the app so that it doesn't migrate its own database on app
startup.  This means that whenever the app runs, something else needs to
ensure the database has been migrated appropriately.  There are four
situations:
- for actual deployment, the start-service.sh script runs the
migration (using a command I manually tested on an existing EC2 box)
- for ./run-application, we have an extra gradle task migrateMainDb
- for functional tests, RegisterRule migrates the database before
running the tests
- for conformance tests, there was already the appropriate usage of
{create,drop}_schema.sh, but the waitForApplicationToStart()
operation broke because the app didn't return a 200 response on the
application port when the database hadn't been migrated already.  I
replaced this with a call …
> migrate database outside of the app itself

- src/main/java/uk/gov/register/resources/EntryResource.java
- src/main/java/uk/gov/register/resources/HttpServletResponseAdapter.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/test/java/uk/gov/register/resources/HttpServletResponseAdapterTest.java
In 4ab4fa32b6b, we added Content-Disposition as a way of controlling
the filename used when downloading data from a register.  Prior to
that commit, if you tried to download
`https://country.register.gov.uk/records.json`, you'd get a file
called `records.json` - afterwards, you got a file called
`country-records.json`.
However, it also had a negative side-effect of forcing download of all
data formats, rather than allowing you to view them in the browser.
I was reading the Content-Disposition RFC (6266) today and I realised
we could set the filename without otherwise changing the browser
behaviour by setting a value of `inline` instead of `attachment`.
Turns out reading the documentation is useful! :grimacing:
I deliberately haven't changed the DataDownloadResource or the RSF
stuff - …
> Serve /entries and /records with `inline` disposition

- src/main/resources/assets/js/analytics-download-type.js
- src/main/resources/assets/js/analytics-external-links.js
- src/main/resources/assets/js/analytics.js
This also fixes external links incorrect filtering when adding JS listeners.
Re-introduces (and fixes) some reverted GA changes from: https://github.com/openregister/openregister-java/pull/97
> This is a fuse of multiple commits to re-enable GA and fix events not being fired properly.

- src/main/java/uk/gov/register/views/AttributionView.java
- src/main/java/uk/gov/register/views/CsvRepresentationView.java
- src/main/java/uk/gov/register/views/EntryListView.java
- src/main/java/uk/gov/register/views/EntryView.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ItemView.java
- src/main/java/uk/gov/register/views/RecordListView.java
- src/main/java/uk/gov/register/views/RecordView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/java/uk/gov/register/views/representations/turtle/EntryListTurtleWriter.java
- src/main/java/uk/gov/register/views/representations/turtle/RecordTurtleWriter.java
- src/main/resources/templates/home.html
- src/main/resources/templates/main.html
As the register history pages show, the "custodian" of a register is a
named individual; while the organisation the custodian belongs to is
known as a "registry".  Our code should use this same language.
I've tested this locally to make sure the templates continue to get
the custodian/registry branding stuff correctly.
> Change "custodian" to "registry"

- src/main/java/uk/gov/register/resources/DeleteRegisterDataResource.java
For consistency with 681d234e1b7bddd03f356ddab80b367de3626702 - we
should configure flyway the same way everywhere.
> Remove another instance of flyway baseline

- src/main/java/uk/gov/register/db/CurrentKeysUpdateDAO.java
- src/main/java/uk/gov/register/exceptions/OrphanItemException.java
- src/main/java/uk/gov/register/exceptions/RootHashAssertionException.java
- src/main/java/uk/gov/register/exceptions/SerializedRegisterParseException.java
- src/main/java/uk/gov/register/providers/OrphanItemExceptionMapper.java
- src/main/java/uk/gov/register/providers/RootHashAssertionExceptionMapper.java
- src/main/java/uk/gov/register/resources/RegisterCommandReader.java
- src/main/java/uk/gov/register/resources/RegisterCommandWriter.java
- src/main/java/uk/gov/register/store/BackingStoreDriver.java
- src/main/java/uk/gov/register/store/postgres/BindEntry.java
- src/main/java/uk/gov/register/store/postgres/BindItem.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriver.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriverNonTransactional.java
- src/main/java/uk/gov/register/store/postgres/PostgresDriverTransactional.java
- src/main/java/uk/gov/register/util/HtmlViewSupport.java
- src/main/java/uk/gov/register/views/representations/turtle/RecordListTurtleWriter.java
- src/test/java/uk/gov/register/core/TransactionalMemoizationStoreTest.java
- src/test/java/uk/gov/register/functional/AnalyticsFunctionalTest.java
- src/test/java/uk/gov/register/resources/DeleteRegisterDataResourceTest.java
- src/test/java/uk/gov/register/resources/RegisterCommandReaderTest.java
- src/test/java/uk/gov/register/service/RegisterSerialisationFormatServiceTest.java
- src/test/java/uk/gov/register/store/postgres/PostgresDriverTransactionalTest.java
almost entirely driven by IntelliJ code inspections:
- remove unused imports
- use Java 8 Function API, not guava
- use singletonList() and emptyList() instead of Arrays.asList()
- remove unused variables
all fairly self-explanatory.
> spring clean

- config.yaml
- src/main/java/uk/gov/register/db/CurrentKeysUpdateDAO.java
- src/main/java/uk/gov/register/db/EntryDAO.java
- src/main/java/uk/gov/register/db/ItemDAO.java
- src/main/java/uk/gov/register/resources/RegisterCommandReader.java
Using the BatchChunkSize annotation seems to avoid memory issues when loading large registers up to and including food-premises-ratings. When doing development its useful to see the sql statements being created by jdbi.
> Set batch chunk size for inserts.

- src/main/java/uk/gov/register/db/EntryIteratorDAO.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/db/EntryIteratorDAOFunctionalTest.java
- src/test/java/uk/gov/register/functional/db/TestEntryDAO.java
- src/test/java/uk/gov/register/resources/RegisterCommandReaderTest.java
- src/test/resources/fixtures/serialized/register-register-rsf.tsv
Sometimes the iterator may not be null but may be already closed. This occurs because we have used the EntryIteratorDAO previously to read up to the end of the iterator (which will close it). This now checks for the closed iterator and recreates it if necessary.
> Fix iterator closed bug

- src/main/java/uk/gov/register/core/RegisterContext.java
Currently, on startup we create all the RegisterContext instances we
need, but we don't check that RegistersConfiguration has the required
RegisterData until the first request is routed to that register.
This changes RegisterContext to pull out the needed RegisterData in
its constructor, which will force the app to fail startup if the
RegisterData can't be found.
> Fail to start if we're missing required RegisterData

- go
In 70291f6f, I added a dependency in `config.yaml` (the local dev
config file) on a new database called `register`, but forgot to update
the `go` script to ensure that it actually exists.
> ensure we create the `register` db

- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/db/TestDBSupport.java
We used to create two separate DataSources per register: one for the
app to use, and a separate one for flyway.  The one created for the
app was created by dbiFactory.build(), which ensures that the
ManagedDataSource instance is correctly registered with the app
lifecycle hooks so that it is shut down when the app shuts down.
The flyway datasource, however, was created manually by us, and we
never register it in the lifecycle hooks.  This means that the app
leaks connections when shut down.  This causes problems when running a
lot of tests, because the collective leaked connections can exhaust
available DB connections and cause test failures.
There are two ways to fix this:
1. register flyway's datasource with the app lifecycle so it gets
closed
2. get flyway to use the same datasource as …
> Bugfix: stop leaking flyway db connections

- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/ItemResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
Adding tests to ensure that entry, item and record pages return a 200 status code when we expect the thing to exist.
> Add functional tests for entry, item and record

- src/main/resources/assets/sass/main.scss
Tables no longer breach the page wrapper
> add scroll css property to tables

- config.yaml
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/test/resources/test-app-config.yaml
Longer-term, I think we're likely to get rid of the default register
configuration items (the top-level things like `database`, `register`,
`enableRegisterDataDelete` etc).  At that point, the name
`otherRegisters` won't make sense any more.
This renames it to plain `registers`.
Nothing is yet consuming this configuration item except the config
files in this repo, so it's a safe rename to do.
> rename `otherRegisters` to `registers`

- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/resources/DeleteRegisterDataResource.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/resources/DeleteRegisterDataResourceTest.java
A few notes about this pull request:
- In `RegisterMemoizationStoreFactory` it would be great if we didn't have to specify the types of `MemoizationStore` that we care about - is it overkill to add a new service which would take these types when the application is registered and loop through this in the factory to create a new store?
- Assumption has been made that we will always be returning an `InMemory` store if the requested type isn't found, but because the factory specifies `<T extends MemoizationStore>` then this should never be the case.
> Demonstrate delete data problem

- src/test/java/uk/gov/register/functional/AnalyticsFunctionalTest.java
- src/test/java/uk/gov/register/functional/ApplicationTest.java
- src/test/java/uk/gov/register/functional/AssetsBundleCustomErrorHandlerTest.java
- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
- src/test/java/uk/gov/register/functional/DataDownloadResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataAvailabilityFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/functional/EntriesResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/FindEntityTest.java
- src/test/java/uk/gov/register/functional/HomePageFunctionalTest.java
- src/test/java/uk/gov/register/functional/ItemResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordListResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/RepresentationsFunctionalTest.java
- src/test/java/uk/gov/register/functional/VerifiableLogResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
- src/test/java/uk/gov/register/functional/app/TestRegister.java
- src/test/java/uk/gov/register/functional/db/EntryIteratorDAOFunctionalTest.java
This introduces an enum `TestRegister`, to capture configuration information about the registers defined in `test-app-config.yaml` and for use with `RegisterRule`.  It means we can pass in an enum value to `getRequest()` and similar methods, rather than passing in a String representing a register.
This will also be useful for my next PR, where I intend to make different register have different basic auth credentials, and TestRegister will be able to hold that data.
> Introduce test register enum

- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
This was dead code -- the DeleteRegisterDataFunctionalTest didn't need
the ConfigOverride at all.  We can now get rid of the
ConfigOverride... constructor from RegisterRule.
> remove last use of ConfigOverride

- src/main/resources/assets/sass/main.scss
Moving the margin to the wrapper to remove the margin above the scroll
bar
> Move table spacing to wrapper

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
Tested locally. The current config.yaml now means that the local
school register has a history page url, but the local register
register does not.
> make historyPageUrl a register-specific config item

- src/test/java/uk/gov/register/functional/VerifiableLogResourceFunctionalTest.java
This adds a test to verify that we don't accidentally share a
MemoizationStore between two different registers -- ie, when we get
proofs from one register, its hashes should be completely different
from the proofs in a different register.
> test independence of MemoizationStores

- README.md
We use StandardJS to lint our JS so adding this to make it more obvious
> Add standardjs badge to readme

- src/main/java/uk/gov/register/db/AbstractEntryLog.java
- src/main/java/uk/gov/register/resources/VerifiableLogResource.java
- src/test/java/uk/gov/register/functional/VerifiableLogResourceFunctionalTest.java
- src/test/java/uk/gov/register/resources/VerifiableLogResourceTest.java
This meant that we were calculating incorrect entry proofs. In the app entry-numbers are one-indexed, but the VerifiableLog library assumes Merkle Tree leaves are zero-indexed. The bug existed because we were not correctly mapping between the two indexed.
It resulted in /proof/entry/1/2/merkle:sha-256 and /proof/entry/2/2/merkle:sha-256 returning the same result.
There was also a problem where we allow /proof/entry/0/2/merkle:sha-256 and /proof/entry/3/2/merkle:sha-256 to be called and they return results (which it shouldn't because these requests do not make sense). We now return a BadRequestException for parameter combinations like this.
> Fix bug where we accidentally use zero-indexed entry-numbers for entry proofs

- src/main/java/uk/gov/register/core/Field.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
This pull request exposes the register's `Field`s through the `HomePageView`. I decided to take the existing field names which are a part of `RegisterMetadata` and map them to actual `Field`s rather than change `RegisterMetadata` to have a `List<Field>`, because this list is actually formed from reading `registers.yaml`, not `fields.yaml`, meaning that we wouldn't have the necessary information available.
> Make field text available to homepage

- src/main/resources/templates/home.html
- src/main/resources/templates/main.html
This commit also removes colons from sidebar titles
> Add Custodian to register home page

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/400.html
- src/main/resources/templates/404.html
- src/main/resources/templates/500.html
- src/main/resources/templates/download.html
- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/home.html
- src/main/resources/templates/item.html
- src/main/resources/templates/not-implemented.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
- Fix font so that we don't reference `nta` at all
- Remove blue underline from header
- Remove blue line from top of right hand column
- Update header background colour to proper blue
- Minor update to right column 'last updated' HTML
> Remove more gov.uk styles

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/core/AllTheRegistersFactory.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/core/RegisterLinks.java
- src/main/java/uk/gov/register/core/RegisterMetadata.java
- src/main/java/uk/gov/register/service/RegisterLinkService.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/service/RegisterLinkServiceTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
This PR adds functionality to calculate links between all registers, exposed through a new `RegisterLinkService` and makes this data available to `HomePageView`. Links between registers will be recalculated when the main register application starts, in addition to on demand through the `/delete-register-data` endpoint when register and field configurations are re-loaded.
> Calculate links to from register

- src/main/resources/templates/home.html
> Add linked registered to homepage

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/core/RegisterContext.java
We shouldn't need to wait for one register's db migration to finish
before starting another.  As each register is a logically independent
entity, it should be okay to run these migrations in parallel.  For
long-running migrations, this should save time.
> run flyway migrations in parallel

- src/main/resources/assets/sass/main.scss
> Fix header for really long register names

- src/main/java/uk/gov/register/RegisterConfiguration.java
I've checked in all our configs, and we don't ever set this to
anything, so we can safely remove this config item.
> remove unused config item

- build.gradle
- dependency-check-suppressions.xml
- external-dependencies.gradle
this adds the [OWASP dependency check][] gradle plugin.  You can run
it using:
./gradlew dependencyCheck
I have also made some changes based on its reports:
- I deliberately exclude the `jrubyExec` configuration because it
doesn't go into the final app artefact; it's only used to compile
sass
- there is a dependency-check-suppressions.xml file which describes
false positives to suppress.  In particular, markdownj-core was
falsely detected as vulnerable to CVE-2012-4232 (which instead
affects jCore), so this has been suppressed.
- there was an alarm (probably false?) for
jackson-dataformat-cbor:2.6.6 due to a transitive dependency from
AWS SDK.  I've added a thing to force it to the same version of
jackson as we use everywhere else.
[OWASP dependency check]: …
> Add dependency-check gradle plugin

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/home.html
Update un-ordered list to definition list for the fields name
> Update field description layout on home page

- config.yaml
- src/main/java/uk/gov/register/filters/LoggingFilter.java
This PR adds a new `Filter` which will use MDC (Mapped Diagnostic Context) to store the current register, so that we can then write this out as part of the log entries. This change will add the register name for all user web requests as the story specifies, but will not add register name to the log entries on app startup (for example, during database migration).
> Log requested register

- src/main/resources/assets/sass/main.scss
> Layout fix for long field names on register home page

- deploy/scripts/start-service.sh
- deploy/scripts/stop-service.sh
This PR sets up a new sidecar container to run `fluentd` and the `fluentd-sumologic plugin` (https://github.com/SumoLogic/fluentd-output-sumologic), then updates the docker container running openregister to use `--log-driver=fluentd`.
> Log openregister via fluentd

- config.yaml
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/configuration/ConfigManager.java
- src/main/java/uk/gov/register/configuration/FieldsConfiguration.java
- src/main/java/uk/gov/register/configuration/RegisterConfigConfiguration.java
- src/main/java/uk/gov/register/configuration/RegistersConfiguration.java
- src/main/java/uk/gov/register/protocols/classpath/ClasspathURLConnection.java
- src/main/java/uk/gov/register/protocols/classpath/Handler.java
- src/main/java/uk/gov/register/util/ResourceYamlFileReader.java
- src/test/java/uk/gov/register/configuration/ConfigManagerTest.java
- src/test/java/uk/gov/register/configuration/FieldsConfigurationTest.java
- src/test/java/uk/gov/register/configuration/RegistersConfigurationTest.java
- src/test/java/uk/gov/register/protocols/classpath/ClasspathURLConnectionTest.java
- src/test/java/uk/gov/register/service/ItemConverterTest.java
- src/test/java/uk/gov/register/service/ItemValidatorTest.java
- src/test/resources/conformance-app-config.yaml
- src/test/resources/test-app-config.yaml
NOT for merging until new config items have been added for test etc. Just for review.
I've added the ability to read classpath://xxx urls and then set the default config items in the project to be classpath urls. This is to reduce the number of Optional objects being passed around when the config is read as the application will complain and fail to start if the config items are missing. I also tidied up a couple of tests.
> Fields location in config

- src/main/java/uk/gov/register/resources/RecordResource.java
The logic in this method was duplicated in ItemCoverter.convertItem()
so it seemed sensible to reuse this.
> Simplify itemContent method logic

- deploy/scripts/start-service.sh
This moves us to the official openjdk docker image, rather than
jstepien/openjdk8.  Currently, the official build is at `u111` while
jstepien/openjdk8 is `u92`.
Also, I picked the alpine-based image.  Alpine is a super minimal
linux environment suitable for running a single process, ideal for our
use case.  (The `openjdk:8-jre` image is based on debian.)
> move to official openjdk docker image

- src/main/resources/templates/download.html
https://trello.com/c/u3VsZtxI/598-make-it-possible-to-download-existing-resources-as-xls
After consultation we've decided to add clearer option on the download page
which ensures people that they download what they know which is
a spreadsheets which still serves CSV underneath.
> Add download spreadsheet (csv) option on download page

- src/main/java/uk/gov/register/core/RegisterContext.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
https://trello.com/c/nkoekkqu/596-register-metadata-fails-to-update-in-some-places-upon-delete-register-data
This fixes the update of the fields. If a user modifies register or field
data and then resets a register (eg by calling `/delete-register-data`)
the register metadata is not being refreshed making home page look the same etc.
The bug was in `RegisterContext` class which was storing `RegisterMetadata`
as field passed in the constructor hence after a reload even though
`ConfigManage`r  had never data Context was still using it's field.
> Refresh register metadata after deleting data fix

- src/main/resources/templates/entries.html
To make sure the breadcrumb is consistent with the record page -
> Update record entry record name in breadcrumb

- src/main/java/uk/gov/register/resources/ItemResource.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/main/java/uk/gov/register/views/ItemView.java
- src/main/java/uk/gov/register/views/RecordView.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/fragments/field-list.html
- src/main/resources/templates/home.html
- src/main/resources/templates/item.html
- src/test/java/uk/gov/register/views/RecordsViewTest.java
- src/test/java/uk/gov/register/views/representations/CsvWriterTest.java
- src/test/java/uk/gov/register/views/representations/TsvWriterTest.java
- src/test/java/uk/gov/register/views/representations/turtle/TurtleRepresentationWriterTest.java
Additionally extracted fields html fragment which can be re-used on multiple pages, sample from homepage:
`<div th:replace="fragments/field-list.html::field-list(${fields})"></div>`
story: https://trello.com/c/SwsyrCzo/619-make-field-descriptions-available-to-records-record-and-item-pages
> Make fields description available on pages (records, record, item)

- deploy/scripts/start-service.sh
Both the fluentd container and the openregister-java container have
the --restart "unless-stopped" option, which means they will be
restarted after a machine reboot.
However, the openregister-java container will fail to start on boot
unless the fluentd container has managed to open its port in time.
This changes the openregister-java container to use the
[fluentd-async-connect][] option, so that if fluentd hasn't started,
the docker daemon will buffer logs until fluentd is available.
There is a potential risk here: if the fluentd container dies, we will
silently not collect logs while the openregister container continues
to run.  I think we could accept this risk for the moment, and look to
remedy in future?  That way we can at least focus on getting automatic
reboots going. …
> don't die if fluentd isn't immediately available

- .gitignore
- README.md
- build.gradle
This configures gradle properly such that
./gradlew compassWatch
will start a task which watches for changes in .scss files and writes
them into the correct path, such that a running app (started with
./run-application.sh) will see the updated css files.
This means we can iterate on scss changes without needed to restart
the app.
> support compassWatch properly

- src/main/java/uk/gov/register/configuration/HomepageContent.java
- src/main/resources/templates/home.html
Also rename the variable to make more sense, since this points to
the tech docs and not the specification.
> Change the URL for the technical documentation to new location

- deploy/scripts/start-service.sh
We struggled to get Docker Hub to create automated builds from GitHub
repos owned by an organization. In the Docker Hub UI we could only see
personal repos and not any repos from organizations we were members of.
In order to get something working we just used a personal GitHub
account. We initially assumed this was due to some weirdness with
permissions/access tokens.
However, it turns out this had nothing to do with permissions (which
makes sense, all our repos are public). After a bit of digging it turns
out you can hit this magical endpoint to create an automated build from
any(?) public repo:
```
https://hub.docker.com/add/automated-build/github/form/{organization}/{repository_name}
```
Source: https://forums.docker.com/t/cant-access-new-github-organization-for-automated-builds/1080/13 …
> Use Docker image owned by the `openregister` organization

- deploy/appspec.yml
Deploying to alpha is currently flakey and it appears to be due to
Flyway migration checks which are very slow. We should look at solving
the problem of why these are slow but at the moment deploying to alpha
is unreliable.
> Temporarily increase the deploy timeout

- build.gradle
- dependency-check-suppressions.xml
- external-dependencies.gradle
- src/main/java/uk/gov/register/core/Entry.java
- src/test/java/uk/gov/register/core/EntryTest.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
This PR adds support for multiple items per entry in the register model. It is a fairly straightforward change, but I will elaborate a little on the modification of the Entry `equals` method.
In order to be able to compare items in the entry, we don't need to worry about what order these item hashes are in. We also allow the possibility of duplicate item hashes per entry, so we can't just store all of these hashes as a set. To get around this problem and not need to re-invent the wheel, I've pulled in the Apache Commons Collection library (http://commons.apache.org/proper/commons-collections/index.html) and am using the method `CollectionUtils.isEqualCollection` to satisfy the above requirements (see the source code at https://commons.apache.org/proper/commons-collections/apidocs/src-html/ …
> Add support to Entry for multiple item hashes

- build.gradle
- external-dependencies.gradle
Version 1.1.7 of logback is getting flagged as having security vulnerabilities. This forces the application to use v1.2.1.
> Force use of v 1.2.1 of log back.

- src/main/java/uk/gov/register/core/Record.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/core/RecordTest.java
We will remove the getters and constructors that allow single items later.
It may also be worth refactoring this record structure at some point as it does
not really represent a domain object - it is more of a view/structure.
> Record should support entries with multiple items

- README.md
- config.docker.yaml
- docker-compose.yml
- run-application.sh
- wait-for-it.sh
Assuming we have people that just want to quickly assess the suitability
of `openregister-java` but are put off because it requires compiling the
app, and installing and configuring Postgres. This simplifies the process
into just one command: `./run-application.sh`.
> Simplify running app locally

- src/main/java/uk/gov/register/core/Entry.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RecordIndex.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/db/AbstractRecordIndex.java
- src/main/java/uk/gov/register/db/EntryItemDAO.java
- src/main/java/uk/gov/register/db/EntryQueryDAO.java
- src/main/java/uk/gov/register/db/ItemQueryDAO.java
- src/main/java/uk/gov/register/db/RecordQueryDAO.java
- src/main/java/uk/gov/register/db/TransactionalEntryLog.java
- src/main/java/uk/gov/register/db/mappers/EntryMapper.java
- src/main/java/uk/gov/register/db/mappers/RecordMapper.java
- src/main/java/uk/gov/register/util/EntryItemPair.java
- src/main/resources/sql/V3__Support_multiple_entries_per_item.sql
- src/test/java/uk/gov/register/db/InMemoryEntryDAO.java
- src/test/java/uk/gov/register/db/TransactionalEntryLogTest.java
- src/test/java/uk/gov/register/db/TransactionalRecordIndexTest.java
- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/db/TestEntryDAO.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
This PR adds a migration to create a new table `entry_item` and insert into it using data currently stored in `entry`. Specifically, it is a join table linking an entry's `entry_number` to an item's `sha256hex`, and this version does not remove `sha256hex` from the entry table - this will happen in a future version.
I've also refactored some of the existing SQL queries to remove stuff like `select`s within `select`s to instead use joins, which should give us better performance and hopefully make it easier to understand what's going on.
`ItemQueryDAO` has also had to change to reflect the addition of the `entry_item` table, and so at the moment `getIterator()` has a `distinct` in the query to only return the unique set of items, rather than the possibility of returning duplicates if an …
> Migration to add new entry_item table

- src/main/resources/sql/V4__Index_on_entry_item_table.sql
This PR adds some missing indexes as a new migration to the `entry_item` table.
> Add index to entry_item table

- src/main/java/uk/gov/register/resources/DataDownload.java
- src/main/java/uk/gov/register/resources/DataUpload.java
- src/main/java/uk/gov/register/resources/DeleteRegisterDataResource.java
- src/main/java/uk/gov/register/resources/EntryResource.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/main/java/uk/gov/register/resources/ItemResource.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/main/java/uk/gov/register/resources/RegisterResource.java
- src/main/java/uk/gov/register/resources/SearchResource.java
- src/main/java/uk/gov/register/resources/VerifiableLogResource.java
This means we output some metrics for each resource, for example for
the `/robots.txt` path we'll start generating metrics that look like the
following:
```
uk.gov.register.resources.HomePageResource.robots
count = 15
mean rate = 1.21 calls/second
1-minute rate = 0.05 calls/second
5-minute rate = 0.01 calls/second
15-minute rate = 0.00 calls/second
min = 0.10 milliseconds
max = 7.64 milliseconds
mean = 0.61 milliseconds
stddev = 1.85 milliseconds
median = 0.12 milliseconds
75% <= 0.14 milliseconds
95% <= 7.64 milliseconds
98% <= 7.64 milliseconds
99% <= 7.64 milliseconds
99.9% <= 7.64 milliseconds
```
At the moment this won't provide a per-register time for these
resources. If we want to do that we'll probably need to change the way
Dropwizard behaves when reflecting over methods with the …
> Time all Dropwizard Resource methods

- src/main/java/uk/gov/register/serialization/mappers/EntryToCommandMapper.java
- src/test/java/uk/gov/register/serialization/mappers/EntryToCommandMapperTest.java
Previously when you downloaded the RSF it would only include the first SHA. This update renders item SHA's individually separated by a ; for each entry.
> Change download-rsf to support multi-item entries

- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RecordIndex.java
- src/main/java/uk/gov/register/db/TransactionalRecordIndex.java
- src/main/java/uk/gov/register/db/UnmodifiableRecordIndex.java
- src/test/java/uk/gov/register/db/TransactionalRecordIndexTest.java
This PR modifies `TransactionalRecordIndex` to allow current keys to be removed and the total record count decremented accordingly. This is to support the feature commonly known as 'tomb-stoning', which may be useful in the context where a register's main dataset is the result of a previous derivation (for example, local authorities by local authority type), where the items stored may change groups over time.
> TransactionalRecordIndex should allow for removal of current keys

- deploy/scripts/validate.sh
This is a temporary hack to minimize the chance of the app being
detected as down by StatusCake. This should only exist for as long as we
are not doing zero-downtime deploys.
:cowboy_hat_face:
> Sleep before deploying to next instance

- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/db/IndexDAO.java
- src/main/java/uk/gov/register/db/IndexQueryDAO.java
- src/main/java/uk/gov/register/indexer/IndexDriver.java
- src/main/java/uk/gov/register/indexer/IndexValueItemPairEvent.java
- src/test/java/uk/gov/register/core/PostgresRegisterTest.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
- src/test/java/uk/gov/register/indexer/IndexDriverTest.java
This PR writes to the new `index` table when entries are being appended to the register (currently `country` and `local-authority-eng` are the only registers which support an index).
Further iterations will specify index functions in config rather than in `PostgresRegister`, in addition to removing the hack from the `indexEntry` method of `IndexDriver` which runs a `commit` on the entire register for every call to it, in order to ensure that all entries are written from the staging list to the database so that we can get records.
> Write to index on append entry

- build.gradle
For what it is worth this doesn't to change what protocol is actually
used--it appears to use HTTPS anyway (global default somewhere?). Either
way it seems better to be explicit about using a secure HTTP connection.
> Use TLS where we can

- requirements.txt
- src/main/java/uk/gov/register/resources/EntryResource.java
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/resources/fixtures/entry.json
- src/test/resources/fixtures/entry.yaml
This makes the entry and entries resources more consistent and allows us to
possibly return multiple entries from this resource in future should it make sense.
We should refactor the view code at some point soon as this could probably be made simpler.
This requires https://github.com/openregister/conformance-test/pull/24 to be merged first and to update `requirements.txt`.
> Change entry resource to return an array

- requirements.txt
- src/main/java/uk/gov/register/views/RecordView.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordMultiItemEntryFunctionalTest.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
- src/test/java/uk/gov/register/views/RecordViewTest.java
- src/test/java/uk/gov/register/views/RecordsViewTest.java
- src/test/resources/fixtures/record.json
- src/test/resources/fixtures/record.yaml
This makes it more consistent with the records resource and means that we can return
multiple records for this resource in the future if appropriate.
At some point we should refactor the record and records view code. It's likely that we can improve it now that both effectively use the same view.
Requires https://github.com/openregister/conformance-test/pull/23 to be merged first (and an update to `requirements.txt`.
> Record resource should now return a result set

- .travis.yml
- build.gradle
This requires [https://github.com/openregister/deployment/pull/329](this) to be deployed first.
CodePipeline seems to require an S3 artifact with a known, constant name. It relies on S3 versioning to reference the different builds of the artifact.
As we're using CodePipeline to trigger CodeDeploy we no longer need to do this from Travis.
> Generate and publish artifact with the same name

- deploy/appspec.yml
We fixed the problem that meant we had to increase this timeout as part
of `9f2daaa6c52541a4c81f99fc707b07db9f76731d` on
`openregister/deployment`.
This reverts commit 80be73aef1349cc65e457c64f30f07d914bb0ca7.
> Revert "Temporarily increase the deploy timeout"

- .travis.yml
Previously, Travis did not provide Postgres 9.5 as an addon. In order to
use this we had to install a version manually (see commit
`e05a0323ec67b65eb2551611c7562afb6d2cd519`).
[Travis now provide Postgres 9.5 as an addon](https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-263550556).
I have a feeling that we should be able to use Travis containers
(setting `sudo: false`) but it appeared to fail silently when I tried
it:
```
$ ./gradlew check
:dependencyCheck
Verifying dependencies for project openregister-java
Checking for updates and analyzing vulnerabilities for dependencies
/home/travis/.travis/job_stages: line 53:  3800 Killed                ./gradlew check
```
The builds also appeared to be slower.
> Use Travis's Postgres addon

- build.gradle
- deploy/appspec.yml
- deploy/scripts/aws/README.md
- deploy/scripts/aws/common_functions.sh
- deploy/scripts/aws/deregister_from_elb.sh
- deploy/scripts/aws/register_with_elb.sh
- deploy/scripts/validate.sh
The scripts to deregister/register instances from the ELB are slightly modified versions of the templates provided by AWS:
https://github.com/awslabs/aws-codedeploy-samples
We will need to deploy https://github.com/openregister/deployment/pull/332 first but these changes should mean we will have zero-downtime deploys provided that no single request lasts longer than the ELB draining TTL.
> Add scripts to deregister/register instances from ELB

- deploy/scripts/aws/common_functions.sh
There is a max length for the names of ELBs; if we have an ELB with the
name `$ENV--$REGISTER-NAME` then the max length is exceeded in the
discovery environment. We specifically deal with this case by trimming
`discovery` to `disco` in our Terraform configuration. We need to mirror
that trimming here too.
> Fix ZDD deploys in discovery environment

- config.docker.yaml
This PR updates `config.docker.yaml` to include schema name, which was added as part of the blitz story to merge databases.
> Fix config to add schema name

- src/test/java/uk/gov/register/functional/app/WipeDatabaseRule.java
- src/test/java/uk/gov/register/functional/db/TestIndexDAO.java
- src/test/java/uk/gov/register/integration/IndexQueryDaoIntegrationTest.java
This PR fixes the index query integration tests (which break when run individually), and uses the `WipeDatabaseRule` to reduce duplication.
> Fix index query integration tests

- run-application.sh
The `stage` task seems to be related to deploying to Heroku. It adds
nothing to the `assemble` task. The `assemble` task seems to be a more
commonly used task name for assembling a `.jar`.
> Make container build use idiomatic gradle

- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RegisterReadOnly.java
- src/main/java/uk/gov/register/db/DerivationRecordIndex.java
- src/main/java/uk/gov/register/db/IndexQueryDAO.java
- src/main/java/uk/gov/register/resources/DerivationRecordResource.java
- src/test/java/uk/gov/register/integration/IndexQueryDaoIntegrationTest.java
This adds a query to IndexQueryDao to count the records in a given index. The result shown for e.g. the local-authorities-by-type index is correct but still looks very strange given the way the index records are rendered.
> Read total number of index records for records view.

- dependency-check-suppressions.xml
This PR fixes the currently breaking build by suppressing vulnerability `CVE-2016-7051` from the dependency check task. `CVE-2016-7051` regards the use of Jackson's `XmlMapper` class, which is not being used either in ORJ or in DropWizard (the latter also has a dependency on Jackson).
The dependency check report generated by this vulnerability is attached to this PR.
[Dependency-Check-Report.pdf](https://github.com/openregister/openregister-java/files/958486/Dependency-Check-Report.pdf)
Note: the various versions of jackson that are being used will hopefully be consolidated once we have upgraded DropWizard from 1.0.2 to 1.1.0.
> Suppress jackson security vulnerability

- build.gradle
- dependency-check-suppressions.xml
- external-dependencies.gradle
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
- src/test/java/uk/gov/register/serialization/RSFExecutorTest.java
- src/test/java/uk/gov/register/service/RegisterSerialisationFormatServiceTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
This PR upgrades DropWizard from version 1.0.2 to 1.1.0 and some of its related dependencies. Certain tests have been modified to remove setup statements that triggered a newly introduced `UnnecessaryStubbingException` in Mockito.
Vulnerabilities `CVE-2015-2808` and `CVE-2013-2566` have been suppressed, as DropWizard uses TLSv1.2 by default and will only include the RC4 cipher if it is explicitly specified in `config.yaml` under an `excludedCipherSuites` property (see https://github.com/dropwizard/dropwizard/blob/9a311914295a5cc81a59f6dc5981286a57b0284f/docs/source/manual/core.rst under heading `SSL`). All vulnerabilities in `tomcat-jdbc-8.5.9.jar` have been suppressed as we do not use Tomcat.
> Upgrade DropWizard to 1.1.0

- deploy/scripts/start-service.sh
Turns out these need to be writeable. After deploying this changes we
see errors of the shape:
```
{ "source":"stderr","log":"/srv/openregister-java/registers.yaml: Read-only file system" }
```
I'm not entirely convinced this should be the case but for the sake of
expediency we'll just make it writeable.
> Make openregister-java container mounts writeable

- go
- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/FindEntityTest.java
- src/test/java/uk/gov/register/functional/app/MigrateDatabaseRule.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
- src/test/java/uk/gov/register/functional/app/TestRegister.java
- src/test/java/uk/gov/register/functional/app/WipeDatabaseRule.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
- src/test/java/uk/gov/register/integration/IndexQueryDaoIntegrationTest.java
See individual commit messages for details.
The gist is that the `go` script created databases in a way that the `postgres` user did not have permission to create new schemas, which the app now needs to be able to do. 
There is also the introduction of a new test rule that performs database migrations for tests that require certain tables to exist. Before this change, whole classes of test would fail intermittently on a fresh database. This should mean hopefully mean that anyone coming to the project for the first time should not see test failures.
> Resolve permission issue for development database

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/filters/HttpToHttpsRedirectFilter.java
- src/test/java/uk/gov/register/functional/ApplicationTest.java
If the application is running behind a load balancer and forwards the
original protocol the user used in the `X-Forwarded-Proto` header and
the original protocol is HTTP then upgrade to HTTPS.
> Redirect HTTP to HTTPS if application is behind a load balancer

- src/main/java/uk/gov/register/core/Record.java
- src/main/java/uk/gov/register/core/RegisterMetadata.java
- src/main/java/uk/gov/register/resources/DerivationRecordResource.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/main/java/uk/gov/register/thymeleaf/ThymeleafView.java
- src/main/java/uk/gov/register/views/RecordView.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/java/uk/gov/register/views/representations/turtle/RecordTurtleWriter.java
- src/main/java/uk/gov/register/views/representations/turtle/RecordsTurtleWriter.java
- src/main/resources/templates/fragments/record-table-item-cells.html
- src/main/resources/templates/fragments/record-table.html
- src/main/resources/templates/record.html
- src/test/java/uk/gov/register/core/RecordTest.java
- src/test/java/uk/gov/register/core/RegisterMetadataTest.java
- src/test/java/uk/gov/register/integration/IndexQueryDaoIntegrationTest.java
- src/test/java/uk/gov/register/views/RecordViewTest.java
- src/test/java/uk/gov/register/views/RecordsViewTest.java
- src/test/java/uk/gov/register/views/representations/CsvWriterTest.java
See individual commit messages for more detail.
This change implements more consistent rules for rendering `/records` and `/record/x` pages that work for both indexes and registers (no matter which is "configured"). The rules in detail are here: https://trello.com/c/N2Q7KGKi/784-make-rendering-of-record-x-and-records-more-consistent-for-registers-and-indexes.
I have attempted to tidy up the RecordView and RecordsViews as I feel that much of the logic belonged in RecordsView - in most formats, the two are now the same.
> Make record(s) rendering consistent for indexes and registers

- build.gradle
- config.docker.basic.yaml
- config.docker.register.yaml
- config.yaml
- external-dependencies.gradle
- src/main/java/uk/gov/register/RegisterApplication.java
This makes it easier to parse/filter/do useful things with the logs
particularly at the point they're being ingested by Sumologic.
> Output Docker logs in JSON format

- deploy/scripts/start-service.sh
This might be useful when diagnosing any future issues. It shouldn't
cost us anything extra series cardinality-wise because we're already
tagging with the host.
```
$ curl http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone
eu-west-1a
```
> Tag metrics with region and availability zone

- src/main/java/uk/gov/register/resources/DataDownload.java
- src/main/java/uk/gov/register/serialization/RSFCreator.java
- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
This PR adds a new endpoint to the DataDownload resource which enables a user to download items and entries from a particular point in time, to the most recent. This saves the user needing to make a separate call to the `/register` endpoint to query the total number of entries held by the register before calling the existing endpoint `/download-rsf/x/y`.
> Add new endpoint to get RSF from specified entry to end of register

- src/main/resources/assets/sass/_organisations.scss
When a gov org logo has no identity i.e. crown, crest or other logo then we should just display plain text with no styling as it break branding guidelines for some orgs i.e. Scottish Government
> Remove org logo border when no logo is present

- src/main/java/uk/gov/register/db/SubstituteSchemaRewriter.java
- src/test/java/uk/gov/register/functional/app/MigrateDatabaseRule.java
- src/test/java/uk/gov/register/functional/app/TestRegister.java
- src/test/java/uk/gov/register/functional/app/WipeDatabaseRule.java
- src/test/java/uk/gov/register/integration/ItemQueryDAOIntegrationTest.java
- src/test/java/uk/gov/register/integration/SchemaSubstitutionIntegrationTest.java
- src/test/resources/test-app-config.yaml
This fixes a bug where the database queries are not properly constructed if the schema name has hyphens.
> Wrap schema name in quotes when substituting

- src/main/java/uk/gov/register/indexer/function/CurrentCountriesIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/LocalAuthorityByTypeIndexFunction.java
With the addition of the new entry type property, we now need to ensure that we only run index functions on the appropriate type of data. For example, we should only run the `current-countries` index function when loading country data into a register, and similarly only run the `metadata` index function when loading system entries into a register.
If we do not check the entry type of incoming entries, we may incorrectly index system entries using any index functions available to the current register.
> Exclude system entries from particular index functions

- school-data.rsf
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/configuration/FieldsConfiguration.java
- src/main/java/uk/gov/register/core/AllTheRegistersFactory.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/exceptions/FieldValidationException.java
- src/main/java/uk/gov/register/exceptions/RegisterValidationException.java
- src/main/java/uk/gov/register/service/EnvironmentValidator.java
- src/main/java/uk/gov/register/service/RegisterSerialisationFormatService.java
- src/main/java/uk/gov/register/util/FieldComparer.java
- src/main/resources/config/fields.yaml
- src/test/java/uk/gov/register/configuration/FieldsConfigurationTest.java
- src/test/java/uk/gov/register/core/PostgresRegisterTest.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataAvailabilityFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RsfRegisterDefinition.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
- src/test/java/uk/gov/register/service/EnvironmentValidatorTest.java
- src/test/java/uk/gov/register/util/FieldComparerTest.java
- src/test/resources/fixtures/example1/index.rsf
- src/test/resources/fixtures/example2/index.rsf
- src/test/resources/fixtures/example3/index.rsf
- src/test/resources/fixtures/local-authority-eng-metadata.rsf
- src/test/resources/fixtures/serialized/register-by-registry.rsf
This PR adds functionality to the register to enable it to validate fields and register definitions, both of an existing register at start-up (through the metadata stored for that register) and when loading an RSF file into an already running register.
> Validate metadata against environment

- src/main/resources/config/fields.yaml
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RsfRegisterDefinition.java
This make the fields.yaml in the project more consistent with the current fields register.
Now we check the field definitions the docker script that launches a local basic instance
was failing as the metadata copied from alpha was not consistent with the internal fields yaml.
> Remove register from registry field

- deploy/scripts/start-service.sh
This means that we can reason about which version of images are running.
We know that it'll be a specific (hopefully immutable) tag and not just
what happens to be "latest" at a given point. This also makes updating
images less tricky—you just update the tag, do a deploy and the new
image gets pulled in.
> Explicitly specify the tag of the Docker image

- src/main/java/uk/gov/register/configuration/IndexFunctionConfiguration.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/indexer/IndexDriver.java
- src/main/java/uk/gov/register/indexer/function/AddAllIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/CurrentCountriesIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/LatestByKeyIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/LocalAuthorityByTypeIndexFunction.java
- src/test/java/uk/gov/register/core/PostgresRegisterTest.java
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
Previously the index functions would check the entry type. This change
associates the index function with an entry type so separate lists of
index functions can be applied as data is loaded.
> Associate index functions with either user and system entry types

- src/main/java/uk/gov/register/configuration/DatabaseManager.java
PaaS have deployed a fix which means this is now available in the JDBC
URI stored in `VCAP_SERIVCES`.
> Remove workaround that ensures the DB connection is encrypted

- manifest.yml
Our configuration is pulled from S3. We no longer need to set these
values here.
> Remove unneeded environment variables

- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RsfRegisterDefinition.java
This fixes a small inconsistency in tests where the register name property was still being called `register-name`, instead of `name` as we have in production.
> Use 'name' in place of 'register-name' everywhere

- external-dependencies.gradle
this pulls in alphagov/dropwizard-logstash#9 which adds `referrer`,
`agent` and `host` fields to the JSON output.  It should be completely
forward-compatible.
> bump version of dropwizard-logstash again

- build.gradle
- deploy/buildspec.yml
- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/address.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
This is very much a (mis)use of CodeBuild.
We currently deploy our code as part of a CodePipeline using CodeDeploy.
CodeDeploy works well with AWS-y things but doesn't have a way a neat
way to deploy to something externally like PaaS.
We can use CodeBuild to run a bunch of `cf` commands to push the `.jar`
to PaaS.
In order to do this our input to the CodeBuild project (the `.zip` that
Travis builds) has to contain a `buildspec.yml` and manifests the
describe the PaaS deployment--this is not ideal and our build artifact
has to know too much about its own deployment.
This feels very much like a stopgap solution to deploying to PaaS and
should be replaced if something more appropriate materializes.
There is a lot of duplication across manifests for different
environments. In the future I …
> Use CodeBuild to deploy to PaaS

- README.md
- RUNNING_LOCALLY.md
- config.docker.register.yaml
- run-application.sh
- scripts/json-to-rsf/json2rsf.py
- scripts/json-to-rsf/readme.md
Previously we cloned the alpha school-eng register when using the `./run-application.sh` script. This is now a reasonably large register that takes a while to load and may also move to the beta environment soon. This change therefore defaults to cloning the beta country register on `./run-application.sh` as this is a smaller and more stable register.
This also adds new documentation on changing the default to clone a different existing register.
The existing documentation for creating a new register locally has been updated to account for metadata changes.
> Default to cloning a smaller register when running locally

- src/main/java/uk/gov/register/RegisterApplication.java
The amount of parallelism is a function of the number of CPU cores
available[1]. When running on our current, but soon to be replaced AWS
infrastructure, the number of available cores is 2. When running on PaaS
the number of available cores is 4. When running on PaaS we see Flyway
sometimes fail to get a database connection from the connection pool
(currently set to 4 in production). This is due to the level of
parallelism consuming all available connections. This manifests itself
as a call to `DataSource.getConnection()` within Flyway returning `null`
and throwing a `FlywayException`[2].
From reading logs it appears that the worker pool on our current AWS
never grows larger than one. It would seem that this hasn't be doing
anything useful on our current infrastructure and we have …
> Remove Flyway migration parallelism

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
This makes it harder to accidentally forget to add a route to both
`beta.openregister.org` and `register.gov.uk`. It also helps DRY things
up a bit.
> Use `domains` and `hosts` in manifest

- dependency-check-suppressions.xml
This will allow us to make deploymeny changes to move from
AWS to PaaS. We will come back to these suppressions and evaluate
the offending dependencies.
> Temporarily suppress dependency check failures

- deploy/manifests/alpha/multi.yml
This register is to replace school-type (which we will remove later)
as there will be a separate register for school-types in scotland.
> Create school-type-eng register in alpha

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
Before moving to PaaS the size of each AWS EC2 instance was 4GB.
This was reduced to 1GB when we moved to PaaS but for no real
reason. Some instances are almost at their memory limit and
it's suspected that this could be causing some issues with
loading and querying data.
> Increase instance size to 4GB

- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/multi.yml
This commit removes `government-domain`, `statistical-geography` and `statistical-geography-unitary-authority-wls` from discovery and alpha, and adds them to beta.
> Update gov-domain and statistical-geography registers phases

- deploy/manifests/alpha/basic.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
We don't need 4GB for the basic instances. This will also ensure
that we do not exceed the organisation memory limit for now. I
have also decreased the memory size in test because there are fewer
registers here
> Decrease memory for basic instances

- src/main/resources/assets/sass/_breadcrumbs.scss
- src/main/resources/templates/download.html
- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/item.html
- src/main/resources/templates/preview.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
- Moves breadcrumbs above "in progress" message below header
- Adds breadcrumbs to the downloads page and removes the back link so the page is consistent with the rest of the pages.
- Also ensures that the "in progress" info on the preview pages only shows for non-beta registers
> Ensure that breadcrumbs sit below header

- src/main/resources/templates/home.html
This change was prompted because of the font size compared to the other pages - 16px vs 19px. By wrapping the page inside a main element we inherit the correct font size and improve accessibility 👍
Thanks for spotting this @karlbaker02
> Fix font size on homepage

- src/main/java/uk/gov/register/resources/PreviewEntriesResource.java
- src/main/java/uk/gov/register/resources/PreviewItemsResource.java
- src/main/java/uk/gov/register/resources/PreviewRecordsResource.java
- src/main/java/uk/gov/register/views/representations/ExtraMediaType.java
- src/main/resources/templates/fragments/download-and-preview-home.html
- src/main/resources/templates/fragments/download-and-preview-single.html
- src/main/resources/templates/fragments/download-and-preview.html
URLs in the HTML pages are using the label 'turtle', they should be using 'ttl' that is the supported format and in this way be more intuitive.
> 'turtle' URLs to 'ttl' URLs

- src/main/java/uk/gov/register/exceptions/FieldConversionException.java
- src/main/java/uk/gov/register/providers/ThrowableExceptionMapper.java
- src/main/java/uk/gov/register/service/ItemConverter.java
- src/main/java/uk/gov/register/views/ViewFactory.java
Catching exception when there is an error converting the data.
Replacing message `500 Error` with `[ERROR] Not possible to process the field (name, data-type, value): organisation, curie, government-organisationD10.`
> Check that exceptions from ItemConverter do not affect all registers

- src/main/resources/templates/preview.html
This page resulted in output with unusual spacing before the comma and
full stop:
The are 4,848 items , this sample shows only the first 100 .
This example text is from:
https://public-body.alpha.openregister.org/preview-records/json
The spacing appears because there is a newline between the comma/full
stop and the previous word in each case.
This commit fixes the issue by ensuring that there is no whitespace
between the previous word and the tag, and no whitespace between the
tag and the comma/full stop.
(I haven't actually tested this - i got a weird compile error when trying to build locally)
> Fix spacing issue

- src/main/resources/templates/preview.html
Content changes:
**Case A**: 1 item
_Before_
_After_
**Case B**: between 2 and 100 items
_Before_
_After_
**Case C**: between 101 and 5000 items
_Before_
_After_
**Case D**: More than 5000 items
_Before_
_After_
> Content updates for 3 register preview pages: JSON, YAML and TTL pages

- src/main/java/uk/gov/migration/R__11_Migrate_current_keys_to_index.java
- src/main/java/uk/gov/register/db/EntryQueryDAO.java
- src/main/java/uk/gov/register/exceptions/EntryValidationException.java
- src/main/java/uk/gov/register/indexer/IndexDriver.java
- src/main/java/uk/gov/register/providers/EntryValidationExceptionMapper.java
- src/main/java/uk/gov/register/store/postgres/PostgresDataAccessLayer.java
- src/main/java/uk/gov/register/store/postgres/PostgresReadDataAccessLayer.java
- src/test/java/uk/gov/register/db/InMemoryEntryDAO.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/indexer/IndexDriverTest.java
This PR adds validation to ensure that identical `append-entry` commands result in a validation error when calling `load-rsf`. The reason for this is because we do not want to append an entry to a register if there is no change from the item(s) assigned against the previous entry for the same key. Doing this ensures that any consumers of the API do not write duplicate data to registers.
> Validate consecutive append entries

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/fragments/footer.html
- src/main/resources/templates/home.html
This commit makes two accessibility fixes: to change the 'Using this register' heading on each register homepage from a `h3` to a `h2`, and to remove the link from the OGL logo in the page footer.
**Heading change:**
Before:
After:
**OGL logo link change:**
Before:
After:
> Accessibility fixes

- src/main/java/uk/gov/register/store/postgres/PostgresDataAccessLayer.java
This PR changes the invocation of `getEntriesByKeys` to pass in the entry keys that have been generated in batches of 1000, as opposed to passing in all of the entry keys (as this defeats the purpose of batching for performace reasons).
> Call getEntriesByKeys for each key batch

- src/main/resources/config/public-bodies.yaml
This PR adds `the-electoral-commission` to `public-bodies.yaml`, as it is defined as the registry by the new `westminster-parliamentary-constituency` register.
> Add the-electoral-commission to public-bodies

- src/main/resources/config/public-bodies.yaml
This PR adds Department for Communities (Northern Ireland) as a new registry, which is required by the `local-authority-nir` register.
> Add Department for Communities (Northern Ireland) as new registry

- run-application.sh
Context: `run-application.sh` failed to run in a clean enviornment due
to missing dependencies stored in git submodules.
Solution: Now `run-application.sh` initialises _and_ updates git
submodules before doing any other work.
> Fix run-application.sh script

- RUNNING_LOCALLY.md
RUNNING_LOCALLY.md suggested cloning the school-type register
from the alpha phase, a register that no longer exists, which
causes errors when using the `run-application.sh` script. This
has now been updated not to specify the exact register, but
detailing where to look for registers that are possible to clone.
> RUNNING_LOCALLY.md should not suggest cloning a non-existent register

- src/main/resources/templates/download.html
- src/main/resources/templates/fragments/footer.html
- src/test/java/uk/gov/register/functional/AnalyticsFunctionalTest.java
This PR adds `analytics-download-type.js` to all pages as part of the footer, so long as the `trackingId` is present in the register config. It is currently only included in `download.html`, which we have moved away from using, meaning that since this change we have had no analytics for download events; this PR fixes this;
> Include download analytics JS on all pages

- deploy/manifests/discovery/multi.yml
This register now exists in alpha so no longer needs to exist
in discovery.
> Remove statistical-geography-council-area-sct from discovery

- deploy/manifests/discovery/multi.yml
The `allergen` register has been promoted to alpha from discovery so can be removed from discovery.
Remove the `allergen` host from the discovery manifest.
> Remove allergen from discovery as it has been promoted to alpha

- CODE_OF_CONDUCT.md
Adds a default code of conduct 1.4 with email `registersteam+code-of-conduct@digital.cabinet-office.gov.uk`.
Let me know if we want to get any inspiration from https://github.com/alphagov/code-of-conduct
> Add code of conduct 1.4

- deploy/manifests/beta/multi.yml
We have approval to promote local-authority-nir from alpha to beta.
Deploy local-authority-nir in beta but leave the alpha one running until we have successfully created it in beta. There will be a separate PR to remove from alpha.
This has been added to the PaaS manifest for beta.
> Create local-authority-nir register in beta

- deploy/manifests/alpha/multi.yml
The public-body custodian has agreed to rename the public-body registers.
- public-body becomes public-body-account
- public-body-classification becomes public-body-account-classification
This should remove the public-body and public-body-classification registers and create public-body-account and public-body-account-classification.
> Rename public-body registers

- .travis.yml
- dependency-check-suppressions.xml
- external-dependencies.gradle
ORJ build was failing for a couple of reasons:
* Travis rolled out a new build <https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch> which uses Python 3.6 and we depended on python 3.5. For now I have added a `group` parameter, to force it to use the old build, however, this should only be a temporary measure while we ideally make the build work with python 3.6
* Postgres CVE. I tried updating to the latest version and the failure still persisted, so I have added a supression rule.
Fixes required to make ORJ build on travis
Build should pass on Travis
> Fix ORJ build

- src/main/java/uk/gov/register/core/LinkResolver.java
- src/main/java/uk/gov/register/core/UriTemplateLinkResolver.java
- src/main/java/uk/gov/register/core/UrlValue.java
- src/main/java/uk/gov/register/service/ItemConverter.java
- src/test/java/uk/gov/register/core/UriTemplateLinkResolverTest.java
- src/test/java/uk/gov/register/service/ItemConverterTest.java
As requested by custodian
Add hyperlink if field datatype is URL. Note, this will only be linked on the `/record` page and not on `/records` as per other link types.
Load record page for record with URL field, should link to URL.
> link urls if datatype url

- config.docker.basic.yaml
- config.docker.register.yaml
- config.yaml
Google has registered `.dev` TLD and put the entire TLD on the HSTS pre-load list. This means in a few weeks once browser updates land non-secure requests to this TLD will start being rejected.
More details: https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd
Switch default local TLD to `.local` as this is TLD is reserved by ICANN. See https://security.stackexchange.com/a/14805
Running ORJ locally should link to e.g.  `field.openregister.local` 
You will need to update any entries in your `/etc/hosts` file to resolve this domain.
> use .local rather than .dev for local TLD

- deploy/manifests/alpha/multi.yml
Remove unrequired registers from alpha.
Remove the following registers from alpha:
- statistical-geography-county-eng		
- statistical-geography-london-borough-eng		
- statistical-geography-metropolitan-counties-eng		
- statistical-geography-metropolitan-district-eng		
- statistical-geography-registration-district-eng		
- statistical-geography-registration-district-wls		
- statistical-geography-non-metropolitan-district-eng		
- statistical-geography-unitary-authority-eng
All registers have been promoted to beta except for `statistical-geography-metropolitan-counties-eng`, which is no longer a register we're working on.
> Remove statistical geography registers from alpha

- deploy/manifests/alpha/multi.yml
Promote `jobcentre-*` and `qualification-*` to alpha. They will be removed from discovery in a separate PR.
Create the following registers in alpha:
- jobcentre
- jobcentre-district
- jobcentre-group
- qualification-assessment-method
- qualification-level
- qualification-sector-subject-area
- qualification-type
https://trello.com/c/mqme6ZLm
https://trello.com/c/LhuqthJP
> Create jobcentre-* and qualification-* registers in alpha

- deploy/manifests/discovery/multi.yml
`qualification-*` and `jobcentre-*` registers have been promoted to alpha.
Remove the following registers from discovery:
- jobcentre
- qualification-assessment-method		
- qualification-level		
- qualification-subject		
- qualification-type
https://trello.com/c/LhuqthJP
https://trello.com/c/mqme6ZLm
> Remove qualification-* and jobcentre registers from discovery

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
- manifest.yml
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/resources/HealthCheckResource.java
This PR creates a new `healthcheck` endpoint which CloudFoundry will be able to use to determine whether the application is healthy. The new endpoint uses the existing `openregister_java` health check created by JDBI when a new `DBI` instance is created as part of the `DatabaseManager`.
When the `openregister_java` health check runs, it attempts to connect to the backing database within 5 seconds and run a `SELECT 1` query - if this is unsuccessful then the application is deemed unhealthy.
A number of options were considered for exposing the health checks that are available within the admin interface of DropWizard:
The first was to simply have CloudFoundry connect to the admin interface via the separate port, however this is not supported by CloudFoundry - it can only connect to the app's …
> Use existing DBIHealthCheck

- .travis.yml
The travis build times out if it does not receive any output after
10 minutes. The registers build can take a long time sometimes due
to the OWASP dependency checker.
This change makes explicit that we use `./gradlew check`
(this is default anyway) and asks travis to wait for the check to
complete. We should look at how to split out or speed up this step in a later PR if we can.
Hoping that this build will pass on travis!
> Instruct travis to not timeout after 10 minutes

- deploy/manifests/discovery/multi.yml
No longer needed or promoted have been promoted up.
cc @elliecraven
> Remove old discovery registers

- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
This PR updates both discovery manifests to add `cloudapps.digital` under as a domain, which will create new routes in paas so that a user can access discovery registers by specifying `<register_name>.cloudapps.digital`. This is a piece of work to enable register creation to happen across the whole team.
> Update discovery manifests

- config.docker.register.yaml
- config.yaml
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/configuration/HomepageContent.java
- src/main/java/uk/gov/register/configuration/HomepageContentConfiguration.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/home.html
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
- src/test/java/uk/gov/register/views/PreviewEntryPageViewTest.java
- src/test/java/uk/gov/register/views/PreviewItemPageViewTest.java
- src/test/java/uk/gov/register/views/PreviewRecordPageViewTest.java
The history no longer exists so there is no need to retain the functionality
Remove anything relating to `historyPageUrl`
Ensure the home page still renders and all tests pass
> Remove history page url from config and views

- deploy/manifests/discovery/multi.yml
We added cloudapps.digital as the domain for discovery but we now want this to be used in a new discovery space and not in the prod space. This is part of the process of moving the discovery environment into a new space.
Remove cloudapps.digital as a domain from the prod space so that it does not clash with the same domain that will be used in a new discovery space.
> Remove cloudapps.digital as domain for discovery

- deploy/manifests/discovery/basic.yml
I forgot to remove this from basic as well as multi.
Don'u use cloudapps.digital as a domain in prod space. This will be moved to discovery space.
> Do not use cloudapps.digital as domain in prod environment

- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
This PR changes the discovery manifests to ensure that all discovery registers point to `cloudapps.digital` instead of `discovery.openregister.org`.
The existing environment will not be affected by this change as our deployment pipeline has changed.
> Switch discovery registers to cloudapps domain

- RUNNING_LOCALLY.md
- run-application.sh
The discovery environment is now available at *.cloudapps.digital and will soon no longer be available at *.discovery.openregister.org. This therefore updates the `run-application.sh` script to work for discovery register at the new location.
Update `run-application.sh` and corresponding `RUNNING_LOCALLY.md` to use new location for discovery registers.
Try following `RUNNING_LOCALLY.md` to clone a register from the discovery environment and that you can access that register locally.
> Change discovery domain

- deploy/manifests/discovery/multi.yml
This PR removes the `domain` and `hosts` properties from the `discovery-multi` manifest, as this will now be modified directly by the creation team via PaaS.
> Remove hosts from discovery manifest

- deploy/buildspec.yml
This PR makes discovery push non zero-downtime, as autopilot removes routes which are not in the manifest, and routes will never be in the manifest for discovery registers.
> Make discovery non zero downtime

- deploy/buildspec.yml
This commit adds the missing single quotes around the new conditional command which performs a regular `cf push` or a `cf zero-downtime-push` depending on the environment.
> Fix conditional logic around pushing app

- external-dependencies.gradle
This PR upgrades Jackson from version 2.8.7 to 2.8.11. This is in response to the recently flagged vulnerability `CVE-2017-17485` (https://nvd.nist.gov/vuln/detail/CVE-2017-17485) which affects `jackson-databind` prior to 2.8.11, in addition to versions 2.9.0 up to and including 2.9.3. We could be affected by this vulnerability if the JSON that we read using `objectMapper.readValue` is crafted to exploit it, which could be achieved via loading registers with a specific payload.
Upgrade Jackson from 2.8.7 to 2.8.11, addressing a specific CVE.
See [report.pdf](https://github.com/openregister/openregister-java/files/1700029/report.pdf) for the generated report.
> Upgrade jackson to 2.8.11

- src/main/java/uk/gov/register/RegisterApplication.java
This PR aims to warm-up the memoisation store for each register as soon as ORJ starts, by computing the root hash of each register. Through doing this, we will remove the burden of users needing to wait for this computation to take place before being able to download the RSF of a register, which should also have the effect of ensuring our caching layer is able to receive a response before timing out (using the current idle and keep-alive settings).
Compute root hash for each register on start-up, asynchronously.
Start-up ORJ locally using a large register (i.e. charity), wait approximately one minute, then hit `/download-rsf`; download should commence almost instantaneously and complete in < 10s (assuming the full charity register).
> Calculate root hash for registers on start-up

- build.gradle
- external-dependencies.gradle
Dependency checker alerted us to a dependency vulnerability.
Explicitly use jackson-databind version 2.8.11.1, which addresses
the vulnerability discussed in CVE-2018-5968
(http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2018-5968).
Check everything builds.
> Address CVE-2018-5968

- src/main/resources/config/public-bodies.yaml
This PR updates _Department for Communities and Local Government_ to _Ministry of Housing, Communities & Local Government_.
> Update DCLG to Ministry of Housing, Communities & Local Government

- src/main/java/uk/gov/register/filters/ConsistencyFilter.java
This commit updates the `ConsistencyFilter` to allow a call to `load-rsf` to bypass it. This is necessary if we need to update the metadata for a register to make it consistent with the environment, as otherwise we are blocked by all requests to an inconsistent register throwing an exception.
> Load RSF should bypass consistency filter

- deploy/manifests/alpha/multi.yml
Because they have been promoted to beta.
Remove from alpha:
- statistical-geography-local-government-district-nir
- jobcentre
- jobcentre-district
- jobcentre-group
> Remove registers from alpha

- deploy/buildspec.yml
This should hopefully fix the issue in code deploy where it cannot perform `apt-get upgrade` as per https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error
Use `apt-get clean` in `buildspec.yml`
We will have to see if it works when we deploy.
> Use `apt-get clean` in `buildspec.yml`

- deploy/buildspec.yml
This PR builds on the previous commits to attempt to fix the currently failing deployments. Specifically, it will force the removal of any cached packages under `apt` to ensure that we are downloading new versions every time. This is taken from https://askubuntu.com/questions/760574/sudo-apt-get-update-failes-due-to-hash-sum-mismatch/760839.
Update `buildspec.yml` to force removal of any cached `apt` packages.
We will see if this works upon deployment.
> Use rm -r /var/lib/apt/lists/* in buildspec.yml

- deploy/buildspec.yml
We are not certain that this did not work previously as the `--fix-broken` option was causing issues with the `apt-get update` command.
As per https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error.
> Use `rm -rf /var/lib/apt/lists/*` in `buildspec.yml`

- deploy/manifests/beta/multi.yml
This commit adds `qualification-assessment-method`, `qualification-level`, `qualification-sector-subject-area` and `qualification-type` registers to the `beta-multi` manifest.
> Add qualification registers to beta

- src/main/resources/assets/sass/main.scss
The item and entry table was too dark
Remove specific styling for these tables. All tables should be consistent.
e.g. https://register.register.gov.uk/item/sha-256:642873fe3929baade4f7c3934f61074cd534aebc5318d7845d120cfd6b31401d
> Remove specific styling for entries table

- src/main/java/uk/gov/register/views/EntryListView.java
- src/main/resources/templates/entries.html
This PR fixes the location of downloads for all formats when a user attempts to download the entries for a particular key. Previously, the download would point to `/entries` for the particular format, meaning that all entries would be downloaded, even when the user would be viewing only entries for some key. This PR now points downloads of this type to `/record/KEY/entries` for the particular format.
Fix download link for entries of a record.
Start ORJ, go to any record, view all versions of this record and then try downloading the resulting entries via the different formats.
> Fix download link for entries of a record

- src/main/java/uk/gov/register/resources/IndexSizePagination.java
- src/main/java/uk/gov/register/resources/Pagination.java
- src/main/java/uk/gov/register/resources/StartLimitPagination.java
- src/main/resources/templates/fragments/download-and-preview.html
This PR fixes a bug for both `/records` and `/entries` which currently leads you to download the wrong data, unless you're viewing page 1 with the default page size of 100 (or for entries, the default `start` of 1 and `limit` of 100).
With this PR, a user wishing to download the particular `/records` they're viewing, say page=3 with page-size=150, will be able to download exactly this data. Similarly, they can download the `/entries` they're viewing, from start=150 with limit=200.
Fix download links for `/records` and `/entries` to include paging info.
Go to `/records`, change `page-index` and `page-size`, then inspect the download URLs and try to download in various formats.
Similarly, for `/entries`, change `start` and `limit`, then inspect the download URLs and try to download in …
> Download should use correct page info

- src/main/java/uk/gov/register/resources/DataDownload.java
Follow up to: https://github.com/openregister/openregister-java/commit/356e94be8eafb08292e0a4b888a38de3ebc6ba56
Fixes #453
Remove `/download` route as associated template was previously removed
`/download` should 404 not 500.
> remove /download route

- src/main/resources/assets/sass/main.scss
Remove `monospace` font and styling overrides
- Remove the `openregister-org` class from the body
- View `/records` on any register with cardinality n fields
> Remove font and styling overrides to cardinality n fields

- src/main/java/uk/gov/register/core/LinkResolver.java
- src/main/java/uk/gov/register/core/LinkValue.java
- src/main/java/uk/gov/register/core/ListValue.java
- src/main/java/uk/gov/register/core/RegisterLinkValue.java
- src/main/java/uk/gov/register/core/UriTemplateLinkResolver.java
- src/main/java/uk/gov/register/core/UrlValue.java
- src/main/java/uk/gov/register/service/ItemConverter.java
- src/test/java/uk/gov/register/core/UriTemplateLinkResolverTest.java
- src/test/java/uk/gov/register/service/ItemConverterTest.java
- src/test/java/uk/gov/register/views/representations/turtle/TurtleRepresentationWriterTest.java
Currently fields with URL datatype cause TTL endpoints to 500. This is due to the below error.
```
"ERROR","level_value":40000,"stack_trace":"java.lang.ClassCastException: uk.gov.register.core.UrlValue cannot be cast to uk.gov.register.core.LinkValue\n\tat uk.gov.register.views.representations.turtle.ItemTurtleWriter$FieldRenderer.renderScalar(ItemTurtleWriter.java:77)
```
This prevents a `ClassCastException` occurring in `ItemTurtleWriter`, which was previously trying to cast a `UrlValue` to a `LinkValue`. This change renames `LinkValue` to `RegisterLinkValue`. Both `UrlValue` and `RegisterLinkValue` now extend the new `LinkValue` class. The UrlTemplateLinkResolver` now resolves `LinkValues`, which prevents casting problems.
Ensure /records.ttl and /item/sha-256:abcde.ttl return a 200 …
>  Fix bug where URL datatypes cause TTL views to return 500

- src/main/resources/config/public-bodies.yaml
"Department for Culture, Media & Sport" is now "Department for Digital, Culture, Media & Sport" and has been renamed here https://www.gov.uk/api/organisations
This might be used as the registry of the data-sharing-agreement registers.  It hasn't yet been used as a registry of any other register.
Rename and re-slug "Department for Culture, Media & Sport" `department-for-culture-media-sport` to "Department for Digital, Culture, Media & Sport" `department-for-digital-culture-media-sport`.
Is it okay to rename these things, or should a new entry be appended instead?
> Rename DCMS to DDCMS

- src/main/java/uk/gov/register/thymeleaf/ThymeleafView.java
- src/main/resources/templates/fragments/global-header.html
The banner was using register name when present, which is long for DSA registers. See https://data-sharing-agreement-0001.cloudapps.digital/.
Use register ID instead of name in the banner.
> Banner should use register ID and not register name

- README.md
- build.gradle
New user getting set up
- make `run-application.sh` script usable even if you use an incompatible shell
- use the correct classpath of module (`openregister-java` without `_main`)
- be agnostic about the pyvenv version (in case you have 3.6 for instance)
The last 2 points are open to discussions, but they're changes I've had to make to get set up.
> Instructions update

- src/main/java/uk/gov/register/store/postgres/PostgresReadDataAccessLayer.java
There was a recent refactor to use the indexing code for both index and "register" actions, including creating RSF. The code that reads the index table makes the assumption that there have been no identical consecutive entries appended to the register. This is not true for the existing government-service register and therefore means that RSF is generated incorrectly for this register.
Revert previous change to use indexing code for generating RSF. This is a temporary solution. Long term we should either fix the history of the government-service register or no longer depend on this rule to generate RSF.
Generating RSF for government-service should not generate multi-item entries. I have tested this by loading the government-service RSF locally and commenting out the code that rejects …
> Iterate on entry table instead of index table to generate RSF

- src/main/java/uk/gov/register/store/postgres/PostgresReadDataAccessLayer.java
See https://github.com/openregister/openregister-java/pull/468 - this fixed `/download-rsf` but did not fix `/download-rsf/n` or `/download-rsf/n/m`.
Fix `/download-rsf/n` or `/download-rsf/n/m` for government-service by reverting away from indexing code.
This should actually work this time.
> Fix /download-rsf/n for registers with identical consecutive entries

- src/main/resources/config/public-bodies.yaml
A new register owned by NHS Digital is going to be created. This means it needs to be in the list of public-bodies.
Currently ORJ uses the GOV.UK API to get logos etc. The current code checks the list of `public-bodies.yml` and also the GOV.UK API for existence of the registry. In the future we should be using the government-organisation register but we haven't done that work yet.
nhs-digital exists here https://www.gov.uk/api/organisations/nhs-digital, which means it should be part of our list of available public-bodies.
Spelling should match https://www.gov.uk/api/organisations/nhs-digital
> Add nhs-digital to list of public-bodies

- src/main/resources/templates/fragments/phase-banner.html
This should mean the link to https://registers.service.gov.uk/registers/{register} should show up for alpha registers.
Fix or statement in thymeleaf
Check it shows up on an alpha register.
> Fix "or" in thymeleaf

- src/main/java/uk/gov/register/core/UriTemplateLinkResolver.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/main/resources/templates/fragments/record-table.html
- src/main/resources/templates/record.html
- src/test/java/uk/gov/register/core/UriTemplateLinkResolverTest.java
Previously the HTML view did not correctly handle linking where the key contains a literal backslash. e.g. https://industrial-classification-2007.cloudapps.digital/records/79.90%2F9
https://trello.com/c/B43trWa3/2025-forward-slashes-arent-url-encoded-in-api-explorer-record-id-links
fix encoding of key link where key contains literal backslash. Although Thymeleaf does URL escape `/` is excluded as it is used to form URL paths, so instead we build the encoded key and pass it into the template.
Key containing literal slash e.g. `79.90/9` should link correctly in HTML view.
> fix encoding of /records/ key link

- docker-compose.register.yml
- run-application.sh
The dockerised version of ORJ uses two Docker Compose config files. The first sets up the network, the second one attaches to it. The problem is that by default Docker Compose relies on the current directory to determine the network name so if you happen to have the project in a directory with another name the setup will break.
Fix the Docker Compose project name to `registers` so the shared network is always `registers_default`.
Run `./run-application.sh` and expect it to deploy two containers with ORJ (8081 and 8080) and one postgres container (5432). Also expect it to clean up itself after stopping the script.
> Fix docker network name

- src/main/resources/assets/sass/_header.scss
- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/fragments/global-header.html
- src/main/resources/templates/fragments/phase-banner.html
- src/test/java/uk/gov/register/functional/AssetsBundleCustomErrorHandlerTest.java
We need to tell our users that GOV.UK Registers as a service is in Aplha
- Add `Alpha` phase tag to header
- Remove the register name
- Remove navigation
View any html page
> Add alpha phase into header

- deploy/manifests/beta/multi.yml
Custodian has approved these registers moving to "ready to use". I'll remove the alpha versions of these registers once we have moved the data to beta.
Add two registers to beta:
- approved-open-standard
- approved-open-standard-guidance
https://trello.com/c/f3cxIHBg/2573-move-approved-open-standards-registers-to-ready-to-use
> Create open-standards registers in beta

- src/main/java/uk/gov/register/serialization/RSFCreator.java
- src/test/java/uk/gov/register/serialization/RSFCreatorTest.java
The /download-rsf/0 endpoint returns system data and user data when a register contains at least one user entry. However when a register does not contain any user entries, /download-rsf/0 does not return any system entries. 
Fix above inconsistency. Also adds tests to ensure system data is included in RSF downloads where it's meant to.
Load a register that only has system entries and no user entries. /download-rsf/0 and /download-rsf/0/0 should return system entries.
> /download-rsf/0 should return system entries for an empty register

- src/main/java/uk/gov/register/resources/DataDownload.java
Previously these routes were subject to default TTL
set 60 second cache headers on these routes to decrease frontend latency
Cache-Control headers should be set on: `curl -I localhost:8080/download-rsf`
DO NOT MERGE until we discuss preferred values/need for performance testing.
> set cache-control headers on DataDownload routes

- deploy/manifests/alpha/multi.yml
- fire-authority is no longer required
- the rest have been promoted to beta
Remove alpha registers
> Remove alpha registers

- src/main/java/uk/gov/register/filters/DeprecatedFormatFilter.java
- src/main/java/uk/gov/register/resources/DerivationRecordResource.java
- src/main/java/uk/gov/register/resources/EntryResource.java
- src/main/java/uk/gov/register/resources/HttpServletResponseAdapter.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/test/java/uk/gov/register/filters/DeprecatedFormatFilterTest.java
- src/test/java/uk/gov/register/functional/RecordListResourceFunctionalTest.java
- src/test/java/uk/gov/register/resources/HttpServletResponseAdapterTest.java
We're deprecating representations that are used less frequently, leaving just JSON and CSV.
The API itself should inform users of the deprecations.
Add the following headers:
- `Link: <https://....json>; rel="alternate"` for .yaml or .ttl
- `Link: <https://....csv>; rel="alternate"` for any .tsv or .xlsx
- `Warning: 299 - "Miscellaneous Persistent Warning" "yaml is deprecated
and will be removed"` for all deprecated formats
Trello: https://trello.com/c/DyKxUdyA/2638-add-format-change-comms-to-api
See also:
- https://tools.ietf.org/html/rfc7234#section-5.5.7
- https://www.iana.org/assignments/link-relations/link-relations.xhtml
We have to use `httpServletResponse` instead of the usual `ContainerResponseContext`, because the pagination code is already adding `Link` headers this way, and …
> Warn about deprecated formats

- src/main/java/uk/gov/register/resources/DataUpload.java
- src/main/java/uk/gov/register/serialization/RegisterResult.java
- src/test/java/uk/gov/register/functional/AuthenticationTest.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/functional/EntriesResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/ItemResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
We used to use the `/load` endpoint to load data into ORJ. We now use `/load-rsf`. 
We are updating the spec so that it doesn't prescribe how entries are minted; see https://github.com/openregister/specification/pull/83
- Remove the load endpoint
- Change tests to use load-rsf instead
I don't plan on deploying this until the corresponding spec change has been merged.
Trello: https://trello.com/c/s2bEdih7/2661-remove-load-endpoint
This'll be easier to review one commit at a time because there's a lot of test changes.
The test code probably needs cleaning up a bit more, but it would be helpful if you could initially give it a quick look over to see if the general approach is OK.
In particular, I had to add a public constructor to RegisterResult so that I could deserialise error responses in …
> Remove load endpoint

- doc/arch/adr-008-items-resource.md
The specification defines a resource (Item collection)[https://openregister.github.io/specification/#items-resource] with an endpoint `/items`.
This ADR proposes a way to address the lack of order the set of items have by providing a first-in index.
> Add ADR008 to define how to implement the items resource

- dependency-check-suppressions.xml
dependency check was failing
- Surpress erroneous stax-api warning
- Remove tomcat suppressions which no longer cause failure
`./gradlew dependencyCheckAnalyze` should be successful.
> fix dependency check

- src/main/java/uk/gov/register/resources/RecordResource.java
- src/test/java/uk/gov/register/functional/RecordResourceFunctionalTest.java
The `Link` header for `/records/{key}` with relation
`rel="version-history"` uses the old url `/record/{key}/entries` instead
of the new one `/records/{key}/entries`.
Trello: https://trello.com/c/333bUFTY/2733-the-link-relation-version-history-shows-the-wrong-old-url
Add an 's'
The link should point to the correct entries resource.
> Correct version history link header

- src/main/java/uk/gov/migration/V__12_Drop_unused_tables.java
These tables were used before we moved to store records as indexes, and
are therefore no longer required.
Trello: https://trello.com/c/dh4sLAJ1/2732-drop-totalrecords-and-currentkeys-tables
This migration drops these tables from a register's schema.
ORJ runs migrations for each schema on startup: https://github.com/openregister/openregister-java/blob/master/src/main/java/uk/gov/register/RegisterApplication.java#L109
- Do I actually need to implement `MigrationChecksumProvider` here? Or is this just for re-runnable migrations?
> Drop total_records and current_keys tables

- doc/arch/adr-009-trailing-slash.md
Currently, HTTP resources have many URLs representing the same thing. This is
not an ideal scenario for search engine indexing or caching.
It proposes a canonical URL per resource.
It should cover all cases.
> ADR009: Trailing slash in HTTP resources

- src/main/java/uk/gov/register/indexer/IndexDriver.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
We should not allow system entries to be loaded into a register where the entry does not change the item in the corresponding record. This is because our indexing code works based on the assumption that this is not possible. We already disallow this for user entries.
Remove the if statement that means the check only applied to user entries.
Check you cannot load duplicate system entries via /load-rsf.
> Disallow duplicate entries for entries with type system

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/filters/StripTrailingSlashRedirectFilter.java
- src/test/java/uk/gov/register/filters/StripTrailingSlashRedirectFilterTest.java
https://github.com/openregister/openregister-java/blob/master/doc/arch/adr-009-trailing-slash.md
Redirect trailing slash paths to non-trailing slash
Note this does not implement `rel=canonical` as suggested in the ADR, as while they were in the same ADR I would rather implement `rel=canonical` in a separate PR.
> Implements ADR009: Trailing slash in HTTP resources 

- .travis.yml
Previously we ran the tests on Oracle JDK
Switch to OpenJDK to be consistent with what we are running on production
Tests should pass on Travis CI
> use openjdk on travis ci

- src/test/java/uk/gov/register/functional/DataDownloadFunctionalTest.java
These tests behave inconsistently between local runs and CI and were creating false positive concerns.
`@Ignore` these tests
Tests should pass in CI. We may wish to make a backlog card to review if we can either make them reliable or delete them entirely.
> @Ignore flaky tests

- manifest.yml
Reverts openregister/openregister-java#512
Now that master has been deployed, we can switch the normal healthcheck back on.
We should change something to avoid master becoming undeployable again, but I don't think this is the right solution long term. https://github.com/openregister/openregister-java/pull/511 was my first attempt at solving this problem, but it turned out to be more complicated than I first thought so I've parked it for now. cc @gidsg
> Revert "Switch off HTTP healthcheck"

- src/main/java/uk/gov/register/resources/RedirectResource.java
- src/test/java/uk/gov/register/resources/RedirectResourceTest.java
We are going to start versioning URLs in line with the [GDS API standards](https://www.gov.uk/guidance/gds-api-technical-and-data-standards#when-you-need-to-make-a-backwards-incompatible-change).
Since we didn't have `/v1/` in the URLs from the beginning, I think it makes sense to keep all the existing resources as they are, but redirect `/v1/` URLs. That way any users who try to construct the v1 URLs based on newer documentation will still get sent to the unversioned resources.
I used a temporary redirect rather than a permanent one because we're redirecting to something with a fixed life expectancy.
- Does this make sense?
- Is there a cleaner way to do this?
- I'm working on the assumption that there will be a v2 of every resource, even if nothing has changed from v1.
- After this my …
> Redirect /v1/ to the unversioned URLs

- src/main/java/uk/gov/register/resources/DeleteRegisterDataResource.java
- src/main/java/uk/gov/register/resources/IndexSizePagination.java
- src/main/java/uk/gov/register/resources/v1/EntryResource.java
- src/main/java/uk/gov/register/resources/v1/ItemResource.java
- src/main/java/uk/gov/register/resources/v1/RecordResource.java
- src/main/java/uk/gov/register/resources/v1/RegisterResource.java
- src/main/java/uk/gov/register/resources/v1/SearchResource.java
- src/main/java/uk/gov/register/resources/v1/VerifiableLogResource.java
- src/main/java/uk/gov/register/resources/v2/EntryResource.java
- src/main/java/uk/gov/register/resources/v2/ItemResource.java
- src/main/java/uk/gov/register/resources/v2/RecordResource.java
- src/main/java/uk/gov/register/resources/v2/RegisterResource.java
- src/main/java/uk/gov/register/resources/v2/SearchResource.java
- src/main/java/uk/gov/register/resources/v2/VerifiableLogResource.java
- src/test/java/uk/gov/register/resources/VerifiableLogResourceTest.java
- src/test/java/uk/gov/register/resources/v1/EntryResourceTest.java
- src/test/java/uk/gov/register/resources/v1/RegisterResourceTest.java
- src/test/java/uk/gov/register/resources/v1/SearchResourceTest.java
- src/test/java/uk/gov/register/resources/v2/EntryResourceTest.java
This builds on top of https://github.com/openregister/openregister-java/pull/515 so I'll need to rebase this once that's merged.
Introduce a /dev/ prefix so we can serve multiple versions of the API at the same time.
Anyone using these endpoints should expect functionality to be
added/removed/changed. Once this version is stable, we will rename
it to /v2/.
As part of this change I've moved the main resource classes (i.e. stuff
that's part of the specified API) to subpackages by version.
I've made IndexSizePagination public so it can be used in both of these
packages (previously it was package private).
As a follow up to this work, we will need to do something with the
conformance tests so that we have the ability to test multiple
versions of the API against their corresponding …
> Add new v2 endpoints

- build.gradle
- requirements.txt
This is a follow up to https://github.com/openregister/conformance-test/pull/31 to make sure the build runs tests for both API versions.
- Use the latest conformance tests
- Run tests for both api versions
`./gradlew check` should run the conformance tests for both versions of the API.
I'm not familiar with gradle so let me know if there's a better way of specifying the relationship between the dependencies here.
> Test both versions of the API

- requirements.txt
- src/main/java/uk/gov/register/core/Record.java
- src/main/java/uk/gov/register/resources/v1/ItemResource.java
- src/main/java/uk/gov/register/resources/v2/BlobResource.java
- src/main/java/uk/gov/register/resources/v2/EntryResource.java
- src/main/java/uk/gov/register/resources/v2/RecordResource.java
- src/main/java/uk/gov/register/views/ItemListView.java
- src/main/java/uk/gov/register/views/ItemView.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/main/java/uk/gov/register/views/v2/EntryListView.java
- src/main/java/uk/gov/register/views/v2/EntryView.java
- src/main/java/uk/gov/register/views/v2/RecordListView.java
- src/main/java/uk/gov/register/views/v2/RecordView.java
- src/test/java/uk/gov/register/views/v2/EntryListViewTest.java
- src/test/java/uk/gov/register/views/v2/EntryViewTest.java
- src/test/java/uk/gov/register/views/v2/RecordListViewTest.java
- src/test/java/uk/gov/register/views/v2/RecordViewTest.java
See corresponding PR for the conformance tests: https://github.com/openregister/conformance-test/pull/32
- Update tests for V2 entry, blob, and record resources to reflect the data model changes.
- Remove some more V2 view code that was only required for HTML views
- Refactored `ItemView` to simplify the resource layer and record view classes a bit
Trello: https://trello.com/c/VUhFKnKy/3033-implement-rfc0024-indexes-removal-breaking-changes
- Nothing should be broken
> Remove indexes from the v2 API

- src/main/java/uk/gov/register/resources/RedirectResource.java
- src/main/java/uk/gov/register/resources/v2/RecordResource.java
- src/test/java/uk/gov/register/resources/RedirectResourceTest.java
This PR addresses a couple of things I overlooked when I introduced API versioning
- Link headers need to preserve the version
- The `/v1` URL should redirect to `/`, even without a trailing slash
Trello: https://trello.com/c/m2QMFk4c/3083-stuff-missing-from-v2-api
- Extend the v1 redirect
- Fix the link between `/records/{record}` and `/records/{record}/entries`
- Remove some HTML support that was still left in the V2 resources (we made the decision not to implement HTML yet)
> Versioning fixes

- doc/arch/adr-011-root-path-handling.md
As part of the work to release the next major version, there are three routes
that need special handling: `/`, `/v1` and `/v2`.
This ADR proposes a behaviour for each one of them.
> ADR011: Propose a method to handle the root paths consistently

- src/main/java/uk/gov/migration/V__14_New_hashing_algorithm.java
- src/main/java/uk/gov/register/db/EntryDAO.java
- src/main/java/uk/gov/register/db/ItemDAO.java
- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/db/TestEntryDAO.java
This is the part of https://trello.com/c/JBenqGkg/3103-implement-rfc0010-item-hashing-algorithm-with-redactability which adds a new item hashing algorithm to ORJ.
Initially, we will store both old and new and hashes, and the new hashes will only be used by the version 2 API.
The first step is to add a column to the schema to store the new hashes. For the moment it will just hold a copy of the old hashes. I will create a separate migration to update these once we've integrated the objecthash algorithm (https://github.com/openregister/objecthash-java)
- This should have no effect on any APIs at this stage
- /load-rsf should still work and should populate the new column
> Add additional hash column

- src/main/java/uk/gov/register/resources/RedirectResource.java
- src/main/java/uk/gov/register/resources/v1/RegisterResource.java
- src/main/java/uk/gov/register/resources/v2/EntryResource.java
- src/main/java/uk/gov/register/resources/v2/RecordResource.java
- src/main/java/uk/gov/register/resources/v2/RegisterResource.java
- src/test/java/uk/gov/register/resources/RedirectResourceTest.java
See https://github.com/openregister/openregister-java/pull/524
https://trello.com/c/m2QMFk4c/3083-stuff-missing-from-v2-api
- Redirect the versioned base path to /register when requesting CSV/JSON
- Redirect /v1 to / when requesting HTML
- Check redirect behaviour against the ADR
- I had to change the paths in the v2 resources for it to pick up the new route
> Implement ADR 11

- src/main/java/uk/gov/register/core/Entry.java
- src/main/java/uk/gov/register/core/EntryLogImpl.java
- src/main/java/uk/gov/register/core/Item.java
- src/main/java/uk/gov/register/core/RegisterImpl.java
- src/main/java/uk/gov/register/db/mappers/EntryMapper.java
- src/main/java/uk/gov/register/resources/v2/BlobResource.java
- src/main/java/uk/gov/register/serialization/mappers/EntryToCommandMapper.java
- src/main/java/uk/gov/register/store/postgres/BatchedPostgresDataAccessLayer.java
- src/main/java/uk/gov/register/store/postgres/BindEntry.java
- src/main/java/uk/gov/register/views/EntryView.java
- src/main/java/uk/gov/register/views/v2/BlobListView.java
- src/main/java/uk/gov/register/views/v2/EntryView.java
- src/test/java/uk/gov/register/core/EntryTest.java
- src/test/java/uk/gov/register/core/RegisterImplTest.java
- src/test/java/uk/gov/register/db/mappers/EntryMapperTest.java
- src/test/java/uk/gov/register/functional/LoadSerializedFunctionalTest.java
- src/test/java/uk/gov/register/views/BlobListViewTest.java
- src/test/java/uk/gov/register/views/v2/EntryViewTest.java
This is part of https://trello.com/c/JBenqGkg/3103-implement-rfc0010-item-hashing-algorithm-with-redactability and follows on from https://github.com/openregister/openregister-java/pull/537
Make the V2 API return hashes from the new `blob_hash` column in `/entries` and `/blobs`, and use this column to resolve the blob lookup for `/blobs/{blob-hash}`.
At the moment, these fields still store the same data as the `sha256Hex` column. This PR only addresses the read part.
- Have I missed any endpoints?
- This should have no effect on production yet, because we're still storing old hashes in the new column - I'll change this in the next PR
- I'll deal with the TODO about removing the old constructor at the end, after I've integrated the new algorithm. This mostly affects tests at the moment, …
> The V2 api should read from the blob-hash columns of item/entry

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/commands/HashDataMigrationCommand.java
Trello: https://trello.com/c/JBenqGkg/3103-implement-rfc0010-item-hashing-algorithm-with-redactability
Now that ORJ supports 2 concurrent hashing algorithms, we can populate the new hashes that will be read by the V2 API.
Add a command to populate `blob_hash` with objecthash hashes for all items, entries, and system entries. Previously `blob_hash` values were set to the V1 hashes.
- I made this a command rather than a migration, because I don't want it to block application startup if it takes a long time to run
- The command is run by passing `migrateHashes config.yaml` as arguments to the jar instead of `server config.yaml`
- It shouldn't matter too much if this command fails to execute, because only the `/next` API reads it, and the update is idempotent
- I used the imperative JDBI …
> Add a DropWizard command to populate v2 hash data

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
I wrote a new data migration, and ORJ is timing out again when trying to start a new instance of the app. 
See
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#timeout
> The timeout attribute defines the number of seconds that Cloud Foundry
> allocates for starting your application. It is related to the
> health-check-type attribute.
>
> You can increase the timeout length for very large apps that require
> more time to start. The timeout attribute defaults to 60, but you can
> set it to any value up to the Cloud Controller’s
> cc.maximum_health_check_timeout property.
I'm raising this value from the default because we force database
migrations to run on startup, and this can cause startup to be
very slow, particularly for "multi" instances, which run
migrations for …
> Wait ages for the application to start

- deploy/manifests/discovery/multi.yml
https://github.com/openregister/openregister-java/pull/544 was not enough to run the migrations on discovery.
Disabling the health check means that the migration can run to
completion, but the app might not actually be reponsive for a while.
> 180s is not enough time to run the latest migration

- src/main/java/uk/gov/register/core/RegisterContext.java
we were erroneously showing the V2 root hash on v1
separate memoization store for v2 to ensure separate values in memory
`proof/register/merkle:sha-256` and `/next/proof/register` should differ.
> separate memoization store for v1 and v2

- requirements.txt
- src/main/java/uk/gov/register/views/v2/RecordListView.java
- src/main/java/uk/gov/register/views/v2/RecordView.java
- src/test/java/uk/gov/register/views/v2/RecordListViewTest.java
- src/test/java/uk/gov/register/views/v2/RecordViewTest.java
https://github.com/openregister/registers-rfcs/blob/master/content/snapshot-resource/index.md
Implements snapshot resource for records. Note this does not implement the extra log size features.
Note, this adds `_id`  at the end of the JSON array and at the start of the CSV as it was easiest to serialise that way. I believe this is spec compliant as per https://spec.openregister.org/v2/rest-api/records but let me know if you feel strongly about this
> Implement RFC0025 Snapshot resource for records

- dependency-check-suppressions.xml
- src/main/java/uk/gov/migration/V__18_ResetSequences.java
In a previous migration (https://github.com/openregister/openregister-java/pull/551) we added this field, and backpopulated the data so that existing blobs had an order value.
I assumed when we updated the data in this way, the sequence would automatically advance its value, but this does not seem to be true in all cases.
On production, we ended up with a register where the latest `blob_order` was 167, but the sequence thought the next value was 164:
```
openregister_java=# select max(blob_order) from item;
max
-----
167
(1 row)
openregister_java=# select nextval('item_item_order_seq');
nextval
---------
164
(1 row)
```
This caused inserts of new blobs to silently fail, because:
1. ORJ tries to insert a row with a duplicate `blob_order`
2. The column has a unique constraint on it, so the …
> Reset the blob order sequence to be in sync with the data

- README.md
- build.gradle
- package-lock.json
- package.json
Everything is broken 😭 
- the compass gem is no longer maintained
- the compass gem pulls in [the latest version of `rb-inotify`](https://github.com/Compass/compass/blob/d5df161d0df7edc686e576b22412f437dd0590cc/cli/compass.gemspec#L22)
- the most recent version of `rb-inotify` [dropped support for old ruby versions](https://github.com/guard/rb-inotify/commit/e3f572ccc807c0e8ca0b5538c41ed70bdfe46918)
- we're running our CI on an outdated ubuntu image, so the build fails with `rb-inotify requires Ruby version >= 2.2.`
- problems with our python dependencies prevent us from updating to a newer image and using a newer jruby version
Replace compass with node-sass.
- Running `npm run sass:compile` should compile the CSS and source map
- It should be equivalent to what we did before with …
> Replace compass with node-sass

- src/main/java/uk/gov/register/resources/RedirectResource.java
- src/test/java/uk/gov/register/resources/RedirectResourceTest.java
We removed tsv, ttl, xlsx and yaml formats at the beginning of december.
If these formats are requested via content type negotiation, ORJ correctly returns `HTTP/1.1 406 Not Acceptable`. But if the user uses an extension in the URL, such as `records.yaml`, they now get a 404 response.
It's more appropriate to return `410 Gone`, since these URLs used to be available but were deliberately removed.
cc @tijmenb
> Return gone for removed formats

- src/main/java/uk/gov/register/serialization/RSFExecutor.java
- src/main/java/uk/gov/register/serialization/RSFFormatter.java
- src/main/java/uk/gov/register/service/EntryValidator.java
- src/test/java/uk/gov/register/functional/DataUploadFunctionalTest.java
- src/test/java/uk/gov/register/service/EntryValidatorTest.java
https://github.com/openregister/registers-rfcs/blob/master/content/entry-key-constraints/index.md
This validates that the entry key only allows IDs.
This PR doesn't include the constraint that an entry key must match the corresponding field in the blob (the field with the same name as the register). I had a go at this but it required a lot of rework of the RSF parsing code.
> Validate entry key

- build.gradle
Followup to #556
Remove unused lines from `build.gradle` we no longer use compass/jruby
> remove unused lines from build.gradle

- build.gradle
- external-dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
Prerequisite to running JDK 11 in Travis CI
* Upgrade to Gradle 5
* Upgrade dependencyCheck plugin to compatible version
* Fix dependencyCheck warnings
Build should pass in Travis CI
> Upgrade to Gradle 5

- src/main/java/uk/gov/register/resources/RedirectResource.java
- src/test/java/uk/gov/register/resources/RedirectResourceTest.java
Bug fix after https://github.com/openregister/openregister-java/pull/561
`/next` was redirecting to `/next/register` which was a 404
`/next` should redirect to `/next/context`
Tests should pass in Travis CI
`/next` should not 404
> fix v2 root redirect

- build.gradle
- external-dependencies.gradle
- src/main/java/uk/gov/register/thymeleaf/ThymeleafViewRenderer.java
master build was failing due to dependency check warning
Upgrade to dropwizard 1.3.8 (and associated changes to support this)
Note: I have removed `dropwizard-graphite` as I don't believe this is being used (since the move to PaaS)
Build should pass on travis
> upgrade dropwizard to 1.3.8

- requirements.txt
fix security warning
bump pyyaml version
github warning should go away after merge. Build should pass in Travis CI.
> bump pyyaml

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
The operating system on PaaS is about to be upgraded. This means we may
find ourselves in a situation where our applications stop working.
We're bumping these ourselves before the change is enforced upon us, to
prepare ourselves for potential additional work.
The manifests are now requesting the underlying OS to be `cflinuxfs3`.
- Sanity check
> Upgrade underlying OS stack

- src/main/resources/assets/js/analytics-init.js
Because Brexit, we've been asked to add a universal GA code to all
government services on a GOV.UK service domain. This does so for
API calls to Registers APIs.
Add a universal GA code that chucks all analytics into the global
GA account.
> Add universal Google Analytics code
