- go
- src/main/java/uk/gov/register/presentation/dao/EntryMapper.java
- src/test/java/uk/gov/register/presentation/dao/EntryMapperTest.java
- src/test/java/uk/gov/register/presentation/functional/EntryResourceFunctionalTest.java
> Timestamp bug fix

- src/main/resources/templates/home.html
https://trello.com/c/8unQ6pVS/326-send-about-registers-link-on-register-front-page-to-new-gov-uk-guidance-page
> Change about register link

- src/main/java/uk/gov/register/db/RecordQueryDAO.java
left `asc` to be very explicit about the choice
> Order record entries by entry number

- doc/arch/adr-004-merging-apps.md
a new Architecture Decision Record documenting why we merged the apps together.
> ADR 4: why we merged the apps together

- .travis.yml
- create_schema.sh
- drop_schema.sh
- src/main/java/uk/gov/register/db/EntryMerkleLeafStore.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/home.html
- src/test/java/uk/gov/register/views/HomePageViewTest.java
- src/test/resources/conformance-app-config.yaml
> Display Register proof coming from verifiable log in fingerprint on the home page

- src/main/java/uk/gov/register/core/RegisterDetail.java
- src/main/java/uk/gov/register/db/EntryQueryDAO.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/RegisterDetailView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/core/RegisterDetailTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
https://trello.com/c/VSAzzqZK/337-register-json-should-not-break-when-there-are-no-entries
> Register endpoint broken for empty db fix

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/main/java/uk/gov/register/resources/VerifiableLogResource.java
- src/main/java/uk/gov/register/service/VerifiableLogService.java
- src/test/java/uk/gov/register/resources/HomePageResourceTest.java
- src/test/java/uk/gov/register/resources/VerifiableLogResourceTest.java
- src/test/java/uk/gov/register/service/VerifiableLogServiceTest.java
https://trello.com/c/psqZ4sRU/341-virifiablelog-service-tech
> Verifiable log service

- src/test/java/uk/gov/register/util/CanonicalJsonMapperTest.java
While I was writing up the item-hash algorithm for the spec, I found a
few edge cases that weren't covered by existing tests.
> add more tests to CanonicalJsonMapperTest

- src/main/java/uk/gov/register/core/RegisterDetail.java
- src/main/java/uk/gov/register/resources/DataDownload.java
- src/main/java/uk/gov/register/resources/RegisterResource.java
- src/main/java/uk/gov/register/views/RegisterDetailView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/test/java/uk/gov/register/core/RegisterDetailTest.java
- src/test/java/uk/gov/register/functional/RegisterResourceFunctionalTest.java
- src/test/java/uk/gov/register/util/ArchiveCreatorTest.java
https://trello.com/c/VDcY5l4d/355-bug-total-items-on-registry-json-is-wrong
> Remove total-items from register view/json

- src/main/resources/assets/sass/_home.scss
- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/main.html
https://trello.com/c/GcnnRKle/334-discovery-phase-registers-don-t-get-a-phase-banner
> Discovery phase tag fix

- src/main/java/uk/gov/register/resources/DataDownload.java
- src/main/java/uk/gov/register/views/DownloadPageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/download.html
- src/test/java/uk/gov/register/filters/ResourceAvailabilityFilterTest.java
- src/test/java/uk/gov/register/functional/DataDownloadResourceFunctionalTest.java
- src/test/java/uk/gov/register/views/DownloadPageViewTest.java
https://trello.com/c/wgvwkgqf/385-address-register-download-page-should-not-return-501
> Download not implemented fix

- build.gradle
- external-dependencies.gradle
> Bump dependencies

- config.yaml
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/configuration/RegisterContentPages.java
- src/main/java/uk/gov/register/configuration/RegisterContentPagesConfiguration.java
- src/main/java/uk/gov/register/views/HomePageView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/home.html
- src/test/java/uk/gov/register/views/HomePageViewTest.java
Configure the link, which may not be present for all registers.
> Link to register history from front page

- build.gradle
- requirements.txt
- src/test/java/uk/gov/register/functional/EntryResourceFunctionalTest.java
And therefore ensure the register name does not need to be slurped from the URL
> Specify register for conformance tests in build.gradle

- src/main/java/uk/gov/register/views/representations/turtle/EntryTurtleWriter.java
- src/test/resources/fixtures/entries.ttl
- src/test/resources/fixtures/entry.ttl
- src/test/resources/fixtures/list.ttl
- src/test/resources/fixtures/record-entries.ttl
- src/test/resources/fixtures/record.ttl
https://trello.com/c/DXsIrbja/497-add-key-to-entry-for-ttl-representation
> Add missing 'key' entry field to 'ttl' format

- doc/arch/adf-006-register-serialization-format.md
Please review. There is no Consequences section at present. I'm not sure if this is needed.
> Rsf decision doc

- src/main/resources/assets/js/analytics-download-type.js
- src/main/resources/assets/js/analytics-external-links.js
- src/main/resources/assets/js/analytics.js
> Revert GA stuff

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/configuration/DeleteRegisterDataConfiguration.java
- src/main/java/uk/gov/register/filters/DeleteRegisterDataFilter.java
- src/main/java/uk/gov/register/resources/DataDeleteNotAllowed.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataAvailabilityFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/java/uk/gov/register/functional/app/RegisterRule.java
- src/test/java/uk/gov/register/resources/HomePageResourceTest.java
https://trello.com/c/chlAXfBX/484-create-endpoint-to-delete-data-from-a-register
to test this add `enableRegisterDataDelete: true` to `config.yaml`
> Delete data from register

- src/main/java/uk/gov/register/resources/DeleteRegisterDataResource.java
- src/main/java/uk/gov/register/resources/HomePageResource.java
- src/test/java/uk/gov/register/resources/DeleteRegisterDataResourceTest.java
- src/test/java/uk/gov/register/resources/HomePageResourceTest.java
> Move /delete-register-data from HomepageResource to it's own resource class

- .travis.yml
https://github.com/travis-ci/travis-ci/issues/6455
> Fix postgres version

- config.yaml
Since we have it may as well update history page for our dev config - usually everything is for schools.
> Change history page to point at shool history page and not country

- build.gradle
- requirements.txt
Moved `head` and added new parameter `--register-domain`
> Update conformance tests to latest

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/java/uk/gov/register/filters/DeleteRegisterDataFilter.java
- src/main/java/uk/gov/register/filters/ResourceAvailabilityFilter.java
- src/test/java/uk/gov/register/filters/ResourceAvailabilityFilterTest.java
- src/test/java/uk/gov/register/functional/DataDownloadResourceFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataAvailabilityFunctionalTest.java
- src/test/java/uk/gov/register/functional/DeleteRegisterDataFunctionalTest.java
- src/test/resources/test-app-config.yaml
This makes the register download and delete endpoints into register-specific config values.
> More register-specific config items

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/main.html
The alpha and beta phase banner were updated in the latest
frontend_toolkit so this refactor removes the deprecation warning. Also
updated the whitespace in the main template file
> Refactor phase banner css

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/entries.html
- src/main/resources/templates/fragments/entry-table.html
- src/main/resources/templates/fragments/item-table.html
- src/main/resources/templates/records.html
Add a parent div tag with overflow scroll to allow horizontal scroll
> Add wrapper to all tables with scroll property

- src/main/resources/templates/record.html
This was causing a type conversion error (between String and RegisterName)
> fix register register template error

- load-school-data.sh
> Add credentials to data loading script as those are required 

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/home.html
> Add field description to home page

- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/home.html
> Add similar registers to home page

- src/main/java/uk/gov/register/RegisterConfiguration.java
- src/main/java/uk/gov/register/configuration/HomepageContent.java
- src/main/java/uk/gov/register/configuration/HomepageContentConfiguration.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterContextFactory.java
- src/main/resources/templates/home.html
- src/test/java/uk/gov/register/core/RegisterContextTest.java
- src/test/java/uk/gov/register/views/HomePageViewTest.java
Changes an `Optional<List<?>>` to a plain `List<?>`, and simplifies a conditional in a template.
> Simplify similar registers

- src/main/java/uk/gov/register/configuration/HomepageContent.java
- src/main/resources/templates/home.html
> Update technical spec link and title on home page

- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/fragments/data-formats.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
- src/test/java/uk/gov/register/functional/FindEntityTest.java
> Move record download links under page header

- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/item.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
- src/test/java/uk/gov/register/functional/FindEntityTest.java
> Make page titles consistent

- src/main/resources/assets/js/details-polyfill.js
- src/main/resources/templates/fragments/footer.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
> Add the field descriptions into record and records view

- src/main/resources/assets/sass/_organisations.scss
You can just about see the difference ;-)
> Add high res organisation logos for retina displays

- src/main/java/uk/gov/register/core/Item.java
- src/main/java/uk/gov/register/indexer/IndexValueItemPair.java
- src/main/java/uk/gov/register/indexer/function/BaseIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/CurrentCountriesIndexFunction.java
- src/main/java/uk/gov/register/indexer/function/IndexFunction.java
- src/main/java/uk/gov/register/indexer/function/LocalAuthorityByTypeIndexFunction.java
- src/main/java/uk/gov/register/resources/DataUpload.java
- src/test/java/uk/gov/register/indexer/IndexValueItemPairTest.java
- src/test/java/uk/gov/register/indexer/function/BaseIndexFunctionTest.java
- src/test/java/uk/gov/register/indexer/function/CurrentCountriesIndexFunctionTest.java
- src/test/java/uk/gov/register/indexer/function/LocalAuthorityByTypeIndexFunctionTest.java
This PR adds some of the functionality that Michaela created in her spike and adds tests for `CurrentCountriesIndexFunction` and `LocalAuthoritiesByTypeIndexFunction`.
> Add and test index functions for local authority, current countries.

- src/main/resources/sql/V5__Create_index_table.sql
Add in index table for derivations.
> Add index table

- config.yaml
- src/main/java/uk/gov/register/core/Entry.java
- src/main/java/uk/gov/register/core/EntryLog.java
- src/main/java/uk/gov/register/core/PostgresRegister.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/core/RegisterReadOnly.java
- src/main/java/uk/gov/register/db/AbstractEntryLog.java
- src/main/java/uk/gov/register/db/DerivationRecordIndex.java
- src/main/java/uk/gov/register/db/IndexQueryDAO.java
- src/main/java/uk/gov/register/db/TransactionalEntryLog.java
- src/main/java/uk/gov/register/db/UnmodifiableEntryLog.java
- src/main/java/uk/gov/register/db/mappers/DerivationEntryMapper.java
- src/main/java/uk/gov/register/db/mappers/DerivationRecordMapper.java
- src/main/java/uk/gov/register/resources/DataDownload.java
- src/main/java/uk/gov/register/resources/DerivationRecordResource.java
- src/main/java/uk/gov/register/serialization/RSFCreator.java
- src/main/java/uk/gov/register/service/RegisterSerialisationFormatService.java
- src/test/java/uk/gov/register/core/InMemoryEntryLog.java
- src/test/java/uk/gov/register/core/PostgresRegisterTest.java
- src/test/java/uk/gov/register/db/InMemoryStubs.java
- src/test/java/uk/gov/register/db/TransactionalEntryLogTest.java
- src/test/java/uk/gov/register/functional/store/postgres/PostgresRegisterTransactionalFunctionalTest.java
- src/test/java/uk/gov/register/integration/IndexQueryDaoIntegrationTest.java
Adding new resource to provide record(s) endpoints for derivations. Added to DownloadData resource to add endpoints to download RSF for derivations.  Extend IndexQueryDAO to read records/entries from the index table storing derivations. Wiring up of classes.
> Derivation download and resource

- src/main/java/uk/gov/register/resources/DerivationRecordResource.java
- src/main/java/uk/gov/register/views/RecordView.java
- src/main/java/uk/gov/register/views/ViewFactory.java
- src/main/resources/templates/fragments/record-table.html
This is to fix the link on the key column where the record is from an Index. It should now point to  /index/[name]/record/[key] rather than /record/[key]
> Correct link on key column in record(s) views

- src/main/resources/config/registers.yaml
This stopped the Field register from working locally using this YAML as
the `fieldsYamlLocaltion`.
> Fix broken YAML

- deploy/scripts/start-service.sh
There should be no need for the container to modify the
directories/files that are mounted.
> Mount volumes with read-only permissions

- README.md
- config.docker.basic.yaml
- config.docker.register.yaml
- docker-compose.basic.yml
- docker-compose.register.yml
- load-school-data.sh
- run-application.sh
> Add script to spin up a register environment locally

- src/main/resources/templates/home.html
> Add information about API usage to register home pages

- RUNNING_LOCALLY.md
Hopefully this will be useful for experimentation with registers.
> Add instructions for running a register locally

- RUNNING_LOCALLY.md
Added specific mention to contact GDS team if users are interested in experimenting with their own registers. Changes made in response to user feedback on Twitter.
> Update README to specify reasons for contact

- run-application.sh
This updates run-application.sh to detect if a container unexpectedly
exits (say, because the configuration is broken) rather than spinning
forever waiting for a port that won't open.
> Detect if a container unexpectedly exits

- README.md
- build.gradle
- manifest.yml
- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/configuration/DatabaseManager.java
- src/main/resources/paas.yaml
It's not a seamless experience but it should be workable in the short-term.
> Enable deploying to PaaS

- config.docker.basic.yaml
- config.docker.register.yaml
- config.yaml
- external-dependencies.gradle
- src/main/resources/paas.yaml
This also adds a new appender that automatically parses out some fields
from the HTTP access logs.
> Update `dropwizard-logstash` to the latest version

- README.md
...as I did not get this out this out the box with [Postgress.app](https://postgresapp.com/)
> document Postgres PATH dependencies

- README.md
...as this did not work out of the box.
> Add IntelliJ run steps

- README.md
- go
...turns out without these the `./gradlew clean build` script fails as follows:
```
Errno::ENOENT on line ["794"] of org/jruby/RubyFile.java: No such file or directory - /Users/gideongoldberg/git/openregister-java/src/main/resources/assets/govuk_frontend_toolkit/stylesheets
Run with --trace to see the full backtrace
:compassCompile FAILED
```
> perform required submodule steps in ./go script

- deploy/buildspec.yml
- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/address.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
We lean on the `cf-blue-green-deploy`[1] to make this as easy as
possible.
[1] https://github.com/bluemixgaragelondon/cf-blue-green-deploy
> Make deploys zero-downtime

- .travis.yml
This is a workaround that hopefully fixes
https://github.com/travis-ci/travis-ci/issues/8363.
> A workaround to fix travis pyenv issue

- src/main/java/uk/gov/register/views/ItemSimpleView.java
- src/main/java/uk/gov/register/views/RecordsView.java
- src/main/resources/templates/fragments/record-table.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
Mainly the structure used to populate the data en in the view was to complex to loop through it. In addition, it was consuming a lot of memory. The data estructure used in the view has been simplified.
> Records page times out when getting 5000 records.

- RUNNING_LOCALLY.md
- config.docker.basic.yaml
Fixes issue #342.
Assign proper default values for beta environments and update the README documentation about how to run it locally.
> Running application from scratch fails

- src/main/resources/assets/sass/_panels.scss
- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/download.html
- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/exception.html
- src/main/resources/templates/fragments/global-header.html
- src/main/resources/templates/fragments/phase-banner.html
- src/main/resources/templates/home.html
- src/main/resources/templates/item.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
> Refactor header and phase banner

- src/main/resources/templates/preview.html
e.g. https://register.alpha.openregister.org/preview-records/json
> fix typo on preview page

- build.gradle
- external-dependencies.gradle
- src/main/java/uk/gov/register/filters/UriDataFormatFilter.java
- src/main/java/uk/gov/register/resources/EntryResource.java
- src/main/java/uk/gov/register/resources/ItemResource.java
- src/main/java/uk/gov/register/resources/RecordResource.java
- src/main/java/uk/gov/register/views/representations/ExtraMediaType.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/EntriesSpreadSheetWriter.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/ItemSpreadSheetWriter.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/RecordSpreadSheetWriter.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/RecordSpreadsheet.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/RecordsSpreadSheetWriter.java
- src/main/java/uk/gov/register/views/representations/spreadsheet/WorkbookGenerator.java
- src/main/resources/templates/download.html
- src/main/resources/templates/fragments/download-and-preview-home.html
- src/main/resources/templates/fragments/download-and-preview-single.html
- src/main/resources/templates/fragments/download-and-preview.html
Adding the possibility to download the records/entries/items in XLSX format.
> implement 'spreadsheets' as a spreadsheet format

- src/main/java/uk/gov/register/filters/ContentSecurityPolicyFilter.java
- src/main/resources/assets/js/analytics.js
- src/test/java/uk/gov/register/functional/ApplicationTest.java
As per other GaaP products i.e. https://github.com/alphagov/paas-product-page/pull/35/files
> Update google analytics tracking rules and csp

- src/main/java/uk/gov/register/service/ItemValidator.java
- src/test/java/uk/gov/register/service/ItemValidatorTest.java
When calling `ItemValidator.validateFieldsValue` on a cardinality
`n` field there was a Null Pointer Exception being thrown by
`JsonNode.textValue()` because it was being called on `JsonArray`.
The offending logic was that checking whther a curie was valid. I
have moved this logic into a submethod that only operates on
individual components and never on a `JsonArray`.
> Fix Null Pointer Exception validating cardinality `n` curie fields

- deploy/manifests/alpha/multi.yml
- statistical-geography-county-eng
- statistical-geography-london-borough-eng
- statistical-geography-metropolitan-counties-eng
- statistical-geography-metropolitan-district-eng
- statistical-geography-registration-district-eng
- statistical-geography-registration-district-wls
- statistical-geography-non-metropolitan-district-eng
- statistical-geography-unitary-authority-eng
> Create 8 new registers in alpha

- deploy/manifests/beta/multi.yml
Create registers in beta
- statistical-geography-county-eng
- statistical-geography-london-borough-eng
- statistical-geography-metropolitan-district-eng
- statistical-geography-registration-district-eng
- statistical-geography-registration-district-wls
- statistical-geography-non-metropolitan-district-eng
- statistical-geography-unitary-authority-eng
These will be removed from alpha in a later PR.
https://trello.com/c/6B3NGQyc
> Create new registers in beta

- deploy/manifests/beta/multi.yml
We have approval for `allergen` register to be made ready to use.
Create `allergen` register in beta.
https://trello.com/c/98CDckcG
> Create allergen register in beta

- deploy/manifests/alpha/multi.yml
`allergen` register has been promoted to beta.
Remove `allergen` register from alpha.
https://trello.com/c/98CDckcG
> Remove allergen from alpha

- deploy/manifests/alpha/multi.yml
Create statistical-geography-local-government-district-nir in alpha
https://trello.com/c/dntnMU21/1664-create-statistical-geography-local-government-district-nir-alpha-enviroment
> Add statistical-geography-local-government-district-nir to alpha

- src/main/resources/assets/js/application.js
- src/main/resources/templates/fragments/footer.html
> Forgot to fire gaap analytics tracking

- deploy/manifests/discovery/multi.yml
These registers are no longer needed and can be removed.
> Remove police-force and police-neighbourhood

- src/main/resources/templates/download.html
- src/main/resources/templates/entries.html
- src/main/resources/templates/entry.html
- src/main/resources/templates/exception.html
- src/main/resources/templates/home.html
- src/main/resources/templates/item.html
- src/main/resources/templates/preview.html
- src/main/resources/templates/record.html
- src/main/resources/templates/records.html
- src/test/java/uk/gov/register/functional/FindEntityTest.java
Accessibility fix 
Move `main` element to top level
`?w=1`
https://github.com/openregister/openregister-java/pull/421/files?w=1
> Move main element to top level

- deploy/manifests/beta/multi.yml
Create statistical-geography-local-government-district-nir in beta
> Create statistical-geography-local-government-district-nir in beta

- deploy/manifests/beta/multi.yml
Approved by custodian.
Create jobcentre, jobcentre-district and jobcentre-group
> Create jobcentre, jobcentre-district and jobcentre-group in beta

- deploy/buildspec.yml
Another attempt to fix the deployment issue.
Use --fix-broken with apt-get update
Hope for the best
> Use --fix-broken with apt-get to fix deploy issues

- deploy/manifests/alpha/multi.yml
> Add fire authority alpha environment

- school-data.rsf
- src/main/java/uk/gov/register/core/datatype/DatatypeFactory.java
- src/main/java/uk/gov/register/core/datatype/DatetimeDatatype.java
- src/main/java/uk/gov/register/core/datatype/PeriodDatatype.java
- src/main/java/uk/gov/register/util/DateFormatChecker.java
- src/test/java/uk/gov/register/core/datatype/PeriodDatatypeTest.java
- src/test/java/uk/gov/register/service/ItemValidatorTest.java
- src/test/java/uk/gov/register/util/DateFormatCheckerTest.java
As per http://openregister.github.io/specification/#period-datatype for the DSA register.
Add a new `PeriodDatatype` and use regex to check format.
Check it's possible to load valid period data but not load invalid period data.
> Add `period` datatype

- src/main/resources/templates/home.html
> Make "View Register" lower case "View register"

- src/main/java/uk/gov/register/store/postgres/PostgresReadDataAccessLayer.java
See https://github.com/openregister/openregister-java/pull/467. I missed the return statement.
Add the return statement.
> Add missing return statement

- deploy/manifests/alpha/multi.yml
https://trello.com/c/GuY5dm0S/2445-create-2-alpha-enviroments
- approved-open-standard
- approved-open-standard-guidance
> Create new alpha registers

- src/main/resources/assets/sass/_header.scss
> Ensure header background is black

- deploy/manifests/alpha/multi.yml
https://trello.com/c/fPHI2eci/2571-create-8-alpha-register-enviromnents
Add new registers to alpha
> Add DDAT register to alpha

- deploy/manifests/beta/multi.yml
Move the ddat registers to beta. I will delete the alpha versions once successfully created in beta.
Move the ddat registers to beta
> Create ddat registers in beta

- doc/arch/adr-008-items-resource.md
I forgot to change the status to this ADR. This PR addresses it.
> Change ADR008 (items pagination) to Accepted (#484)

- README.md
Update README to include loading data into development environment.
> Update readme to include step for loading data

- src/main/resources/templates/fragments/register-intro.html
Required for access the data changes
Remove API key reference
Check text is as expected.
> remove api key reference

- README.md
- src/main/resources/assets/sass/_notice.scss
- src/main/resources/assets/sass/main.scss
- src/main/resources/templates/fragments/global-header.html
Sister PR to https://github.com/openregister/registers-frontend/pull/380
Add notice to readme, text taken from https://github.com/openregister/registers-frontend/pull/380
Check text
> Add format deprecation notice

- src/main/resources/config/public-bodies.yaml
Required for new discovery register
add DIT public body
> add DIT public body

- deploy/manifests/beta/multi.yml
> add ISA registers to beta

- build.gradle
Supersedes #525 
Bump guava sub-dependency
build should pass in travis ci
> bump guava sub-dependency

- deploy/manifests/alpha/multi.yml
add fe colleges alpha registers
> add fe colleges alpha registers

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
- manifest.yml.sample
Missed a closing bracket in https://github.com/openregister/openregister-java/pull/531 🤦‍♂️ 
Fix syntax
Hopefully will deploy on PaaS
> add missing closing bracket

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
- manifest.yml.sample
> revert JRE 11

- deploy/manifests/discovery/multi.yml
https://github.com/openregister/openregister-java/pull/545 didn't work - the app doesn't listen on the port until its finished starting.
Switch to process based healthcheck so this migration can actually run
> Temporarily disable healthcheck

- deploy/manifests/alpha/basic.yml
- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/basic.yml
- deploy/manifests/beta/multi.yml
- deploy/manifests/discovery/basic.yml
- deploy/manifests/discovery/multi.yml
- deploy/manifests/test/basic.yml
- deploy/manifests/test/multi.yml
> Restore normal healthcheck

- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/multi.yml
Add new beta registers and remove old alpha versions
> Add new beta registers and remove old alpha versions

- .travis.yml
- build.gradle
- src/test/java/uk/gov/register/store/postgres/BatchedPostgresDataAccessLayerTest.java
- src/test/java/uk/gov/register/store/postgres/PostgresDataAccessLayerTest.java
https://trello.com/c/OfChhRGO/1628-update-orj-build-to-python-36
* Use Ubuntu Xenial
* Use Python 3.6 native virtualenv
* Test fixes
* Build should pass in Travis CI
> Upgrade Travis build to Ubuntu Xenial and Python 3.6

- README.md
reflect requirements change after https://github.com/openregister/openregister-java/pull/565
update readme
> update readme as no longer need pyvenv

- src/test/java/uk/gov/register/functional/db/EntryIteratorFunctionalTest.java
- src/test/java/uk/gov/register/protocols/s3/S3URLConnectionTest.java
- src/test/java/uk/gov/register/resources/HttpServletResponseAdapterTest.java
- src/test/java/uk/gov/register/resources/RequestContextTest.java
- src/test/java/uk/gov/register/resources/v1/EntryResourceTest.java
- src/test/java/uk/gov/register/resources/v2/EntryResourceTest.java
- src/test/java/uk/gov/register/serialization/RSFExecutorTest.java
- src/test/java/uk/gov/register/serialization/handlers/AddItemCommandHandlerTest.java
- src/test/java/uk/gov/register/service/RegisterSerialisationFormatServiceTest.java
- src/test/java/uk/gov/register/thymeleaf/ThymeleafViewTest.java
- src/test/java/uk/gov/register/util/HtmlViewSupportTest.java
- src/test/java/uk/gov/register/util/ObjectReconstructorTest.java
making app more future-proof
Fix mockito deprecation warnings
Tests should pass in Travis CI
> fix mockito deprecation warning

- src/main/java/uk/gov/register/RegisterApplication.java
- src/main/java/uk/gov/register/core/RegisterContext.java
- src/main/java/uk/gov/register/db/RecordQueryDAO.java
- src/main/java/uk/gov/register/thymeleaf/ThymeleafContext.java
- src/main/java/uk/gov/register/util/ArchiveCreator.java
- src/test/java/uk/gov/register/functional/db/TestEntry.java
- src/test/java/uk/gov/register/providers/JsonParseExceptionMapperTest.java
future proof app
Fix Guava deprecation warning, see https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate#why-we-deprecated-throwablespropagate for full details
Build should pass in Travis CI app should still run
> fix guava throwables deprecation

- src/main/java/uk/gov/register/AssetsBundleCustomErrorHandler.java
- src/main/java/uk/gov/register/RegisterApplication.java
Thymeleaf deprecation warning
Fix thymeleaf deprecation warning
Should no longer show thymeleaf warning
> fix thymeleaf deprecation warning

- src/main/java/uk/gov/register/AssetsBundleCustomErrorHandler.java
- src/main/java/uk/gov/register/RegisterApplication.java
Reverts openregister/openregister-java#572
(try reverting this to resolve production issue)
> Revert "fix thymeleaf deprecation warning"

- src/main/java/uk/gov/register/AssetsBundleCustomErrorHandler.java
- src/main/java/uk/gov/register/RegisterApplication.java
Reverts openregister/openregister-java#575
this was a red herring
> Revert "Revert "fix thymeleaf deprecation warning""

- deploy/manifests/alpha/multi.yml
- deploy/manifests/beta/multi.yml
> Promote to beta

- deploy/buildspec.yml
> Fix pipeline
